insert into agents (aname, city, percent) values ('Scott Larson', 'Trenton', 0.69);
insert into agents (aname, city, percent) values ('Evelyn Tucker', 'Spokoynaya', 0.77);
insert into agents (aname, city, percent) values ('Charles Thomas', 'Sinfra', 0.98);
insert into agents (aname, city, percent) values ('Annie Palmer', 'Saint-Augustin-de-Desmaures', 0.56);
insert into agents (aname, city, percent) values ('Douglas Carpenter', 'San Pedro Zacapa', 0.05);
insert into agents (aname, city, percent) values ('Robert Ryan', 'Cururupu', 0.57);
insert into agents (aname, city, percent) values ('Brandon Howard', 'Amparafaravola', 0.82);
insert into agents (aname, city, percent) values ('Debra Hawkins', 'Tianhe', 0.09);
insert into agents (aname, city, percent) values ('Sarah Brooks', 'Jasienica', 0.87);
insert into agents (aname, city, percent) values ('Brenda Jordan', 'Bintang', 0.15);
insert into agents (aname, city, percent) values ('Amy Garza', 'Charenton-le-Pont', 0.76);
insert into agents (aname, city, percent) values ('Jimmy Riley', 'Yako', 0.16);
insert into agents (aname, city, percent) values ('Ryan Rose', 'Mellila', 0.83);
insert into agents (aname, city, percent) values ('Nancy Hawkins', 'Mengzhai', 0.16);
insert into agents (aname, city, percent) values ('Sharon Wells', 'Timurlorong', 0.91);
insert into agents (aname, city, percent) values ('Philip Cunningham', 'Pasirmalang', 0.81);
insert into agents (aname, city, percent) values ('Katherine Riley', 'Herzliya Pituah', 0.74);
insert into agents (aname, city, percent) values ('Jesse Harvey', 'Campos Sales', 0.32);
insert into agents (aname, city, percent) values ('Tammy Schmidt', 'Portland', 0.48);
insert into agents (aname, city, percent) values ('Kathleen Griffin', 'Washington', 0.86);
insert into agents (aname, city, percent) values ('Robin Robinson', 'Surovikino', 0.18);
insert into agents (aname, city, percent) values ('Marilyn Collins', 'Hantsport', 0.44);
insert into agents (aname, city, percent) values ('Brandon Peters', 'Tsurib', 0.61);
insert into agents (aname, city, percent) values ('Todd Cook', 'Morani', 0.63);
insert into agents (aname, city, percent) values ('Stephen Payne', 'Claveria', 0.6);
insert into agents (aname, city, percent) values ('Denise Moreno', 'Lannion', 0.39);
insert into agents (aname, city, percent) values ('Chris West', 'Lypnyazhka', 0.06);
insert into agents (aname, city, percent) values ('Frank Harper', 'Kool Tengah', 0.95);
insert into agents (aname, city, percent) values ('Frances Wallace', 'Tanudan', 0.66);
insert into agents (aname, city, percent) values ('Virginia Harrison', 'San Rafael del Sur', 0.25);
insert into agents (aname, city, percent) values ('Larry Alexander', 'Uthai Thani', 0.32);
insert into agents (aname, city, percent) values ('Steven Harrison', 'Shreveport', 0.14);
insert into agents (aname, city, percent) values ('Louise Davis', 'Terpsithéa', 0.88);
insert into agents (aname, city, percent) values ('Denise Murray', 'Bastan', 0.88);
insert into agents (aname, city, percent) values ('Jerry Hughes', 'Alexandria', 0.42);
insert into agents (aname, city, percent) values ('Sarah Vasquez', 'Catalão', 0.01);
insert into agents (aname, city, percent) values ('Ruby Medina', 'Rotunda', 0.92);
insert into agents (aname, city, percent) values ('Janice Lane', 'Xinminxiang', 0.27);
insert into agents (aname, city, percent) values ('Gary Webb', 'Alfonso', 0.97);
insert into agents (aname, city, percent) values ('Mildred Gonzales', 'Concepción del Uruguay', 0.49);
insert into agents (aname, city, percent) values ('Jonathan Coleman', 'Nanggewer', 0.56);
insert into agents (aname, city, percent) values ('Russell Palmer', 'Dehī', 0.45);
insert into agents (aname, city, percent) values ('Dennis Gordon', 'Cruz de Pau', 0.99);
insert into agents (aname, city, percent) values ('Norma Rivera', 'Rangxi', 0.12);
insert into agents (aname, city, percent) values ('Katherine Stevens', 'Clifden', 0.15);
insert into agents (aname, city, percent) values ('Phyllis Hansen', 'Hanjiaji', 0.6);
insert into agents (aname, city, percent) values ('Emily Johnston', 'Baoxing', 0.08);
insert into agents (aname, city, percent) values ('Carol Hunter', 'Tanlad', 0.53);
insert into agents (aname, city, percent) values ('Steve Alvarez', 'Podbrdo', 0.54);
insert into agents (aname, city, percent) values ('Adam Taylor', 'Tysmenytsya', 0.41);
insert into agents (aname, city, percent) values ('Paula Black', 'Laguna de Perlas', 0.11);
insert into agents (aname, city, percent) values ('Aaron Howard', 'Kōnan', 0.87);
insert into agents (aname, city, percent) values ('Ernest Schmidt', 'Ágios Pétros', 0.96);
insert into agents (aname, city, percent) values ('Bobby Fowler', 'Sanbaishan', 0.91);
insert into agents (aname, city, percent) values ('Cynthia Brooks', 'Genova', 0.02);
insert into agents (aname, city, percent) values ('Wanda Long', 'Dawan', 0.2);
insert into agents (aname, city, percent) values ('Patrick Burke', 'Petrovskoye', 0.21);
insert into agents (aname, city, percent) values ('Angela Cunningham', 'Klina', 0.87);
insert into agents (aname, city, percent) values ('Brian Romero', 'Obihiro', 0.75);
insert into agents (aname, city, percent) values ('Phillip Murphy', 'Brongkah', 0.17);
insert into agents (aname, city, percent) values ('Sarah Payne', 'Santa Luzia', 0.04);
insert into agents (aname, city, percent) values ('Louis Mills', 'Naḩḩālīn', 0.7);
insert into agents (aname, city, percent) values ('Lori Brown', 'Santa Lucía', 0.99);
insert into agents (aname, city, percent) values ('Nancy Ray', 'Khantaghy', 0.28);
insert into agents (aname, city, percent) values ('Victor Simmons', 'Sridadi', 0.16);
insert into agents (aname, city, percent) values ('Juan Jackson', 'Ampahana', 0.4);
insert into agents (aname, city, percent) values ('Amanda Richards', 'Boje', 0.71);
insert into agents (aname, city, percent) values ('Tammy Crawford', 'Brooklyn', 0.08);
insert into agents (aname, city, percent) values ('Eric Ward', 'Curahkalak Tengah', 0.29);
insert into agents (aname, city, percent) values ('Christine Wagner', 'Photharam', 0.86);
insert into agents (aname, city, percent) values ('Martha Hanson', 'Lühua', 0.97);
insert into agents (aname, city, percent) values ('Bruce Bryant', 'Ramat HaSharon', 0.96);
insert into agents (aname, city, percent) values ('Teresa Turner', 'Pásion', 0.81);
insert into agents (aname, city, percent) values ('Phyllis Perkins', 'Melekyne', 0.15);
insert into agents (aname, city, percent) values ('Michelle Gordon', 'Chateaubelair', 0.09);
insert into agents (aname, city, percent) values ('Linda Powell', 'Domont', 0.04);
insert into agents (aname, city, percent) values ('Phyllis Martinez', 'Cimaung Kidul', 0.28);
insert into agents (aname, city, percent) values ('Katherine Baker', 'Sentani', 0.87);
insert into agents (aname, city, percent) values ('Julia Tucker', 'Siwa Oasis', 0.34);
insert into agents (aname, city, percent) values ('Dorothy Nelson', 'Tonggakjati', 0.95);
insert into agents (aname, city, percent) values ('Harold Robinson', 'Mitú', 0.09);
insert into agents (aname, city, percent) values ('Daniel Sanders', 'Longxian Chengguanzhen', 0.91);
insert into agents (aname, city, percent) values ('Brenda Montgomery', 'Nong Khaem', 0.64);
insert into agents (aname, city, percent) values ('Carlos Little', 'Dushan', 0.86);
insert into agents (aname, city, percent) values ('Jose Peterson', 'Hilversum', 0.2);
insert into agents (aname, city, percent) values ('Evelyn Bradley', 'Veldhoven', 0.02);
insert into agents (aname, city, percent) values ('Catherine Watson', 'Bahía de Caráquez', 0.87);
insert into agents (aname, city, percent) values ('Nancy Scott', 'Hongos', 0.74);
insert into agents (aname, city, percent) values ('Laura Dunn', 'Katakwi', 0.95);
insert into agents (aname, city, percent) values ('Ryan Allen', 'Noisy-le-Grand', 0.28);
insert into agents (aname, city, percent) values ('Carl Hawkins', 'Kolchikón', 0.01);
insert into agents (aname, city, percent) values ('Sara Thomas', 'Nunmanu', 0.9);
insert into agents (aname, city, percent) values ('Walter Price', 'Magadan', 0.81);
insert into agents (aname, city, percent) values ('Keith Washington', 'Kuressaare', 0.08);
insert into agents (aname, city, percent) values ('Louise Peterson', 'Kalanchak', 0.49);
insert into agents (aname, city, percent) values ('Walter Pierce', 'Mississauga', 0.72);
insert into agents (aname, city, percent) values ('Diane Burns', 'Ishkhoy-Yurt', 0.42);
insert into agents (aname, city, percent) values ('Raymond Peters', 'El Retén', 0.16);
insert into agents (aname, city, percent) values ('Melissa Dixon', 'Ribeirão Preto', 0.79);
insert into agents (aname, city, percent) values ('Robert Turner', 'Daniëlskuil', 0.62);
insert into agents (aname, city, percent) values ('Rose Howard', 'Xianzong', 0.36);
insert into agents (aname, city, percent) values ('Juan Mcdonald', 'Nice', 0.5);
insert into agents (aname, city, percent) values ('Justin Fields', 'Xinfeng', 0.71);
insert into agents (aname, city, percent) values ('Frances Brown', 'Pietermaritzburg', 0.78);
insert into agents (aname, city, percent) values ('Kathy Olson', 'Nouvelle France', 0.37);
insert into agents (aname, city, percent) values ('Keith Carter', 'Banyuurip', 0.07);
insert into agents (aname, city, percent) values ('Lisa Little', 'Helong', 0.91);
insert into agents (aname, city, percent) values ('Carolyn Scott', 'Nis’oni', 0.14);
insert into agents (aname, city, percent) values ('Jeffrey Gray', 'Jember', 0.84);
insert into agents (aname, city, percent) values ('Jonathan Sanders', 'Banī Khaddāsh', 0.99);
insert into agents (aname, city, percent) values ('Chris Morales', 'Shaguotun', 0.26);
insert into agents (aname, city, percent) values ('Doris Jenkins', 'Żernica', 0.97);
insert into agents (aname, city, percent) values ('Jessica Vasquez', 'Myeik', 0.17);
insert into agents (aname, city, percent) values ('Richard Johnston', 'Vale de Figueira', 0.47);
insert into agents (aname, city, percent) values ('Richard Carroll', 'San Pa Tong', 0.19);
insert into agents (aname, city, percent) values ('Nicholas Moreno', 'Caijiazha', 0.5);
insert into agents (aname, city, percent) values ('Russell Wells', 'Jaša Tomić', 0.28);
insert into agents (aname, city, percent) values ('Brian Matthews', 'Ulanov', 0.43);
insert into agents (aname, city, percent) values ('Earl Stephens', 'Estreito Câmara de Lobos', 0.6);
insert into agents (aname, city, percent) values ('Matthew Cook', 'Langkapcaang Hilir', 0.28);
insert into agents (aname, city, percent) values ('Harold Lee', 'Dateng', 0.42);
insert into agents (aname, city, percent) values ('Carlos Johnston', 'Qeshm', 0.93);
insert into agents (aname, city, percent) values ('Joshua Larson', 'Julcamarca', 0.66);
insert into agents (aname, city, percent) values ('Steven Williams', 'Armstrong', 0.88);
insert into agents (aname, city, percent) values ('Michael Lopez', 'Shuakhevi', 0.19);
insert into agents (aname, city, percent) values ('Brian Gomez', 'Tuchengzi', 0.47);
insert into agents (aname, city, percent) values ('Denise Sullivan', 'Saraza', 0.09);
insert into agents (aname, city, percent) values ('Sarah Spencer', 'Magdeburg', 0.59);
insert into agents (aname, city, percent) values ('Russell Harper', 'Cangkreng', 0.71);
insert into agents (aname, city, percent) values ('Irene Bailey', 'Batugede Kulon', 0.81);
insert into agents (aname, city, percent) values ('Julie Daniels', 'Shun’ga', 0.87);
insert into agents (aname, city, percent) values ('Ryan Greene', 'Amboanjo', 0.21);
insert into agents (aname, city, percent) values ('Lori Armstrong', 'Xugu', 0.5);
insert into agents (aname, city, percent) values ('Karen Watkins', 'Kudang', 0.66);
insert into agents (aname, city, percent) values ('Jeremy Perkins', 'Tullich', 0.63);
insert into agents (aname, city, percent) values ('Lawrence Thomas', 'Omaha', 0.87);
insert into agents (aname, city, percent) values ('Martha George', 'Bollnäs', 0.39);
insert into agents (aname, city, percent) values ('Evelyn Gordon', 'Căuşeni', 0.58);
insert into agents (aname, city, percent) values ('Carlos Cooper', 'Pitrufquén', 0.81);
insert into agents (aname, city, percent) values ('Rachel Ford', 'Sława', 0.71);
insert into agents (aname, city, percent) values ('Clarence Turner', 'Banocboc', 0.83);
insert into agents (aname, city, percent) values ('Lillian Little', 'Montélimar', 0.4);
insert into agents (aname, city, percent) values ('Gloria Warren', 'Franca', 0.41);
insert into agents (aname, city, percent) values ('Timothy Montgomery', 'Sentani', 0.21);
insert into agents (aname, city, percent) values ('Tammy Alexander', 'Huangcai', 0.4);
insert into agents (aname, city, percent) values ('Teresa Thompson', 'Albany', 0.85);
insert into agents (aname, city, percent) values ('Edward Sullivan', 'Manyana', 0.02);
insert into agents (aname, city, percent) values ('Paula Bennett', 'Varazqān', 0.89);
insert into agents (aname, city, percent) values ('Sharon Hughes', 'Carhuac', 0.68);
insert into agents (aname, city, percent) values ('Amy Lee', 'Shakhty', 0.24);
insert into agents (aname, city, percent) values ('Sean Garrett', 'San Vicente', 0.13);
insert into agents (aname, city, percent) values ('Philip Payne', 'Daijiaba', 0.6);
insert into agents (aname, city, percent) values ('Ruth White', 'Santana', 0.11);
insert into agents (aname, city, percent) values ('Cynthia Cunningham', 'Venustiano Carranza', 0.07);
insert into agents (aname, city, percent) values ('Harold Welch', 'Sv. Trojica v Slov. Goricah', 0.54);
insert into agents (aname, city, percent) values ('Stephanie Chapman', 'Larangan', 0.84);
insert into agents (aname, city, percent) values ('Sara Watkins', 'Pinillos', 0.61);
insert into agents (aname, city, percent) values ('Michael Wagner', 'Pingdi', 0.53);
insert into agents (aname, city, percent) values ('Susan Gonzales', 'Ono', 0.42);
insert into agents (aname, city, percent) values ('Shirley Dean', 'Roermond', 0.6);
insert into agents (aname, city, percent) values ('Lawrence Hicks', 'Puerto La Cruz', 0.09);
insert into agents (aname, city, percent) values ('Barbara Davis', 'Marcos Juárez', 0.77);
insert into agents (aname, city, percent) values ('Antonio Kim', 'Isla Pucú', 0.37);
insert into agents (aname, city, percent) values ('Ronald Cook', 'Batuidu', 0.71);
insert into agents (aname, city, percent) values ('Lois Anderson', 'Moglicë', 0.05);
insert into agents (aname, city, percent) values ('Todd White', 'Malāyer', 0.0);
insert into agents (aname, city, percent) values ('Timothy Ray', 'Magog', 0.69);
insert into agents (aname, city, percent) values ('Julia Martin', 'Grand Rapids', 0.64);
insert into agents (aname, city, percent) values ('Louise Gibson', 'Kurume', 0.63);
insert into agents (aname, city, percent) values ('Gary Medina', 'Sinchao', 0.85);
insert into agents (aname, city, percent) values ('Carolyn Owens', 'Libenge', 0.23);
insert into agents (aname, city, percent) values ('Emily Clark', 'Owerri', 0.8);
insert into agents (aname, city, percent) values ('Louis Rice', 'Campaka', 0.22);
insert into agents (aname, city, percent) values ('Ralph Young', 'Wailang', 0.82);
insert into agents (aname, city, percent) values ('Michael Black', 'Les Coteaux', 0.54);
insert into agents (aname, city, percent) values ('Sharon Ruiz', 'Yangsha', 0.62);
insert into agents (aname, city, percent) values ('Annie Montgomery', 'Netrakona', 0.61);
insert into agents (aname, city, percent) values ('Anthony Flores', 'Cishangang', 0.99);
insert into agents (aname, city, percent) values ('Margaret Morales', 'Taochuan', 0.96);
insert into agents (aname, city, percent) values ('Juan Burns', 'Rancapanjang', 0.79);
insert into agents (aname, city, percent) values ('Marie Kelley', 'Banjar Bongangede', 0.16);
insert into agents (aname, city, percent) values ('Marie Brooks', 'Montecillo', 0.96);
insert into agents (aname, city, percent) values ('Larry Arnold', 'Wasagu', 0.33);
insert into agents (aname, city, percent) values ('Carolyn Mccoy', 'Pustomyty', 0.78);
insert into agents (aname, city, percent) values ('Joan Wilson', 'Weixin', 0.07);
insert into agents (aname, city, percent) values ('William Walker', 'Enschede', 0.48);
insert into agents (aname, city, percent) values ('Philip Perkins', 'Bor', 0.62);
insert into agents (aname, city, percent) values ('Kenneth Hunter', 'Batas Barat', 0.78);
insert into agents (aname, city, percent) values ('Laura Hicks', 'Cimitarra', 0.24);
insert into agents (aname, city, percent) values ('Heather Jenkins', 'Stęszew', 0.87);
insert into agents (aname, city, percent) values ('Phyllis Andrews', 'São Brás de Alportel', 0.16);
insert into agents (aname, city, percent) values ('Phillip Bradley', 'Liangshuihe', 0.07);
insert into agents (aname, city, percent) values ('Ernest Price', 'Ciriri', 0.16);
insert into agents (aname, city, percent) values ('Gregory Price', 'Kachia', 0.45);
insert into agents (aname, city, percent) values ('Irene Wallace', 'Doujia', 0.64);
insert into agents (aname, city, percent) values ('John Hill', 'Mirzec', 0.96);
insert into agents (aname, city, percent) values ('Lillian Gibson', 'Lenakapa', 0.7);
insert into agents (aname, city, percent) values ('Henry Morris', 'Kildare', 0.63);
insert into agents (aname, city, percent) values ('Alice Brooks', 'Santa Catalina', 0.24);
insert into agents (aname, city, percent) values ('Bruce Morris', 'Camilaca', 0.47);
insert into agents (aname, city, percent) values ('Janice Reid', 'Kista', 0.44);
insert into agents (aname, city, percent) values ('Kimberly Berry', 'Tuusula', 0.84);
insert into agents (aname, city, percent) values ('Craig King', 'Clarin', 0.83);
insert into agents (aname, city, percent) values ('Henry Weaver', 'Raga', 0.68);
insert into agents (aname, city, percent) values ('Ann Freeman', 'Mashan', 0.25);
insert into agents (aname, city, percent) values ('Anna Gonzales', 'Sokol', 0.82);
insert into agents (aname, city, percent) values ('Terry Scott', 'Biała Piska', 0.36);
insert into agents (aname, city, percent) values ('Ruby Hawkins', 'Uzunovo', 0.64);
insert into agents (aname, city, percent) values ('Julie Kennedy', 'Kimito', 0.52);
insert into agents (aname, city, percent) values ('Janet Torres', 'Quxi', 0.31);
insert into agents (aname, city, percent) values ('Robin Lee', 'Dasha', 0.85);
insert into agents (aname, city, percent) values ('Gloria Murray', 'Nankang', 0.14);
insert into agents (aname, city, percent) values ('Donald Willis', 'Donghai', 0.44);
insert into agents (aname, city, percent) values ('Craig Brown', 'Baiqi', 0.78);
insert into agents (aname, city, percent) values ('Nicholas Price', 'Pérama', 0.52);
insert into agents (aname, city, percent) values ('Angela Simmons', 'Jojoima', 0.43);
insert into agents (aname, city, percent) values ('Joshua Bowman', 'Dolní Dvořiště', 0.98);
insert into agents (aname, city, percent) values ('Adam Holmes', 'Soca', 0.67);
insert into agents (aname, city, percent) values ('Carlos Boyd', 'Dacheng', 0.72);
insert into agents (aname, city, percent) values ('Gregory Thomas', 'Orlu', 0.76);
insert into agents (aname, city, percent) values ('Todd Lawrence', 'Fovissste', 0.27);
insert into agents (aname, city, percent) values ('Christine Gray', 'Walnut Grove', 0.84);
insert into agents (aname, city, percent) values ('Albert Nguyen', 'Ningyuan', 0.69);
insert into agents (aname, city, percent) values ('Joshua Montgomery', 'Saint Helier', 0.01);
insert into agents (aname, city, percent) values ('Juan Hayes', 'Xinpu', 0.18);
insert into agents (aname, city, percent) values ('Katherine Mills', 'Sexmoan', 0.72);
insert into agents (aname, city, percent) values ('Sandra Ellis', 'Quỳ Châu', 0.47);
insert into agents (aname, city, percent) values ('Jonathan Morrison', 'San Fernando Apure', 0.42);
insert into agents (aname, city, percent) values ('Scott Gonzalez', 'Baoxing', 0.58);
insert into agents (aname, city, percent) values ('Bruce Cook', 'Waepana', 0.32);
insert into agents (aname, city, percent) values ('Aaron Wagner', 'Frederiksberg', 0.03);
insert into agents (aname, city, percent) values ('Carol Duncan', 'Ciénaga', 0.41);
insert into agents (aname, city, percent) values ('Ruth Patterson', 'Cut-cut Primero', 0.09);
insert into agents (aname, city, percent) values ('Amy Howard', 'Xialaba', 0.33);
insert into agents (aname, city, percent) values ('Diana White', 'Gjilan', 0.89);
insert into agents (aname, city, percent) values ('Jeffrey Dunn', 'Perth', 0.75);
insert into agents (aname, city, percent) values ('Bobby Richards', 'Jalālābād', 1.0);
insert into agents (aname, city, percent) values ('Michelle Coleman', 'Tras Cerros', 0.17);
insert into agents (aname, city, percent) values ('Wanda Johnston', 'Santa Ana', 0.69);
insert into agents (aname, city, percent) values ('Jack Bowman', 'Puerto Maldonado', 0.92);
insert into agents (aname, city, percent) values ('Eric Price', 'Mingelchaur', 0.06);
insert into agents (aname, city, percent) values ('Matthew Ellis', 'Telouet', 0.58);
insert into agents (aname, city, percent) values ('Lawrence Rodriguez', 'Klagenfurt am Wörthersee', 0.4);
insert into agents (aname, city, percent) values ('Chris Ward', 'Limanowa', 0.55);
insert into agents (aname, city, percent) values ('Susan Fox', 'Longtou', 0.99);
insert into agents (aname, city, percent) values ('Christina James', 'Comal', 0.68);
insert into agents (aname, city, percent) values ('Earl Phillips', 'Sabana de Parra', 0.66);
insert into agents (aname, city, percent) values ('Albert Banks', 'Médanos', 0.92);
insert into agents (aname, city, percent) values ('Susan Davis', 'Szczytno', 0.8);
insert into agents (aname, city, percent) values ('William Wood', 'Créteil', 0.78);
insert into agents (aname, city, percent) values ('Laura Williams', 'Yihe', 0.87);
insert into agents (aname, city, percent) values ('Wayne Taylor', 'Mosjøen', 0.99);
insert into agents (aname, city, percent) values ('Wanda Banks', 'Borås', 0.42);
insert into agents (aname, city, percent) values ('Justin Mccoy', 'Hudson Bay', 0.16);
insert into agents (aname, city, percent) values ('Paul Ortiz', 'Lillehammer', 0.91);
insert into agents (aname, city, percent) values ('Kathleen Kelley', 'Ōkuchi', 0.29);
insert into agents (aname, city, percent) values ('Joshua Montgomery', 'Drayton Valley', 0.6);
insert into agents (aname, city, percent) values ('Jeremy Rogers', 'Calilegua', 0.66);
insert into agents (aname, city, percent) values ('Bobby Alexander', 'Patos Fshat', 0.76);
insert into agents (aname, city, percent) values ('Jennifer Alexander', 'Mungging', 0.45);
insert into agents (aname, city, percent) values ('Gloria Ramirez', 'Gent', 0.92);
insert into agents (aname, city, percent) values ('Brenda Cole', 'Santa Rita', 0.83);
insert into agents (aname, city, percent) values ('Chris Cooper', 'Lamalera', 0.07);
insert into agents (aname, city, percent) values ('Raymond Patterson', 'Tengjia', 0.37);
insert into agents (aname, city, percent) values ('Mildred Bryant', 'Qingshan', 0.27);
insert into agents (aname, city, percent) values ('Michael Carter', 'Biankouma', 0.79);
insert into agents (aname, city, percent) values ('Brenda Scott', 'Baiyang', 0.19);
insert into agents (aname, city, percent) values ('Paul Harvey', 'Le Pontet', 0.23);
insert into agents (aname, city, percent) values ('Anne Stewart', 'Logroño', 0.32);
insert into agents (aname, city, percent) values ('Christopher Johnston', 'Kalangbret', 0.59);
insert into agents (aname, city, percent) values ('Jane Henry', 'Stavanger', 0.38);
insert into agents (aname, city, percent) values ('Katherine Moreno', 'Długosiodło', 0.29);
insert into agents (aname, city, percent) values ('Dorothy Stone', 'Dongfeng', 0.41);
insert into agents (aname, city, percent) values ('James Olson', 'Mechrá Belqsiri', 0.3);
insert into agents (aname, city, percent) values ('Helen Hunter', 'Jeziora Wielkie', 0.28);
insert into agents (aname, city, percent) values ('Philip Armstrong', 'Thap Khlo', 0.69);
insert into agents (aname, city, percent) values ('Clarence Young', '‘Abs', 0.02);
insert into agents (aname, city, percent) values ('Anne Burke', 'Chuquitira', 0.2);
insert into agents (aname, city, percent) values ('Emily Clark', 'Kista', 0.88);
insert into agents (aname, city, percent) values ('Juan Wheeler', 'Svenljunga', 0.54);
insert into agents (aname, city, percent) values ('Christina Cole', 'Guanqian', 0.08);
insert into agents (aname, city, percent) values ('Larry Fields', 'Nogueira da Regedoura', 0.1);
insert into agents (aname, city, percent) values ('Barbara Sanders', 'Eséka', 0.14);
insert into agents (aname, city, percent) values ('Roy Cole', 'Vlachovice', 0.43);
insert into agents (aname, city, percent) values ('Martha Roberts', 'Волочаевское', 0.21);
insert into agents (aname, city, percent) values ('Brian Gibson', 'Jiamachi', 0.78);
insert into agents (aname, city, percent) values ('Kelly Johnston', 'Bagong Sikat', 0.97);
insert into agents (aname, city, percent) values ('Russell Alexander', 'Pniewy', 0.05);
insert into agents (aname, city, percent) values ('Pamela Phillips', 'Vale das Mós', 0.28);
insert into agents (aname, city, percent) values ('Kimberly Lawrence', 'Tsévié', 0.11);
insert into agents (aname, city, percent) values ('Timothy Palmer', 'Coro', 0.25);
insert into agents (aname, city, percent) values ('Angela Wheeler', 'Aqqan', 0.8);
insert into agents (aname, city, percent) values ('Marilyn Richards', 'Gjirokastër', 0.22);
insert into agents (aname, city, percent) values ('William Smith', 'Núi Sập', 0.46);
insert into agents (aname, city, percent) values ('Nancy Smith', 'Youlongchuan', 0.16);
insert into agents (aname, city, percent) values ('Walter Chapman', 'Dengjiang', 0.38);
insert into agents (aname, city, percent) values ('Kelly Brown', 'Ciomas', 0.82);
insert into agents (aname, city, percent) values ('Frances Mccoy', 'Buzuluk', 0.81);
insert into agents (aname, city, percent) values ('Gerald Ryan', 'Tha Mai', 0.66);
insert into agents (aname, city, percent) values ('Kelly West', 'Hanyuan', 0.41);
insert into agents (aname, city, percent) values ('Kathryn Willis', 'Cotonou', 0.08);
insert into agents (aname, city, percent) values ('Ruth Larson', 'Liangzeng', 0.15);
insert into agents (aname, city, percent) values ('Peter Fisher', 'Xincheng Chengguanzhen', 0.87);
insert into agents (aname, city, percent) values ('Angela Boyd', 'Jagna', 0.74);
insert into agents (aname, city, percent) values ('Doris Richards', 'La Sebala du Mornag', 0.05);
insert into agents (aname, city, percent) values ('Roy Meyer', 'Craigavon', 0.97);
insert into agents (aname, city, percent) values ('Alice Mendoza', 'Linxia Chengguanzhen', 0.95);
insert into agents (aname, city, percent) values ('Ashley Richardson', 'Sancha', 0.39);
insert into agents (aname, city, percent) values ('Linda Mendoza', 'Banjar Sambangan', 0.15);
insert into agents (aname, city, percent) values ('Mildred Franklin', 'Wuppertal', 0.62);
insert into agents (aname, city, percent) values ('Juan Hall', 'Matiompong', 0.36);
insert into agents (aname, city, percent) values ('Kevin Sanchez', 'Concepción', 0.68);
insert into agents (aname, city, percent) values ('Steve Chavez', 'Brandfort', 0.01);
insert into agents (aname, city, percent) values ('Rose Burns', 'Deqing', 0.12);
insert into agents (aname, city, percent) values ('Juan Payne', 'Capellanía', 0.48);
insert into agents (aname, city, percent) values ('Ralph Brown', 'San Miguel de Tucumán', 0.99);
insert into agents (aname, city, percent) values ('Rebecca Holmes', 'Glinojeck', 0.18);
insert into agents (aname, city, percent) values ('Steve Wells', 'Isojoki', 0.21);
insert into agents (aname, city, percent) values ('Carlos Watkins', 'Bununu Dass', 0.95);
insert into agents (aname, city, percent) values ('Doris Fields', 'Teutônia', 0.66);
insert into agents (aname, city, percent) values ('Arthur Torres', 'Tupaciguara', 0.48);
insert into agents (aname, city, percent) values ('Kelly Wheeler', 'Monte Francisco', 0.4);
insert into agents (aname, city, percent) values ('Jerry Brooks', 'Wanliang', 0.71);
insert into agents (aname, city, percent) values ('Keith Gibson', 'Durazno', 0.43);
insert into agents (aname, city, percent) values ('Dennis Jackson', 'Herong', 0.63);
insert into agents (aname, city, percent) values ('Brian Hart', 'Huaqiao', 0.41);
insert into agents (aname, city, percent) values ('Amanda Hicks', 'Zhengyangshan', 0.42);
insert into agents (aname, city, percent) values ('Sara Stewart', 'Mali Iđoš', 0.39);
insert into agents (aname, city, percent) values ('Andrew Morales', 'Vysotsk', 0.53);
insert into agents (aname, city, percent) values ('Sean Gonzalez', 'Rejoyoso', 0.51);
insert into agents (aname, city, percent) values ('Jennifer Sanders', 'Xixiang', 0.17);
insert into agents (aname, city, percent) values ('Diana Cunningham', 'Créteil', 0.01);
insert into agents (aname, city, percent) values ('Bonnie Richards', 'Caminauit', 0.12);
insert into agents (aname, city, percent) values ('Robin Boyd', 'Zhexiao', 0.37);
insert into agents (aname, city, percent) values ('Lois Cox', 'Purwasari', 0.97);
insert into agents (aname, city, percent) values ('Kevin Hamilton', 'Kiltamagh', 0.45);
insert into agents (aname, city, percent) values ('Craig Lee', 'Tarrafal de São Nicolau', 0.26);
insert into agents (aname, city, percent) values ('Victor Austin', 'Skövde', 0.59);
insert into agents (aname, city, percent) values ('Eric George', 'Genova', 0.43);
insert into agents (aname, city, percent) values ('Henry Green', 'Malausma Kidul', 0.29);
insert into agents (aname, city, percent) values ('Edward Baker', 'Trairi', 0.57);
insert into agents (aname, city, percent) values ('Rachel Burke', 'Al Lagowa', 0.73);
insert into agents (aname, city, percent) values ('Kathleen Romero', 'Pampa Hermosa', 0.21);
insert into agents (aname, city, percent) values ('Robin Fisher', 'Carrascal', 0.79);
insert into agents (aname, city, percent) values ('Raymond Davis', 'Camrose', 0.4);
insert into agents (aname, city, percent) values ('Janet Jenkins', 'Konëvo', 0.59);
insert into agents (aname, city, percent) values ('Antonio Bowman', 'Alès', 0.54);
insert into agents (aname, city, percent) values ('Alan Nguyen', 'Syriam', 0.63);
insert into agents (aname, city, percent) values ('Carlos Thomas', 'Iktābah', 0.73);
insert into agents (aname, city, percent) values ('Juan Wilson', 'Milwaukee', 0.18);
insert into agents (aname, city, percent) values ('Donald Fox', 'Beigang', 0.31);
insert into agents (aname, city, percent) values ('Aaron Cruz', 'Izbicko', 0.24);
insert into agents (aname, city, percent) values ('Edward Jones', 'Asahikawa', 0.69);
insert into agents (aname, city, percent) values ('Jean Simmons', 'Koryčany', 0.28);
insert into agents (aname, city, percent) values ('Joe Fisher', 'Jeseník', 0.83);
insert into agents (aname, city, percent) values ('Tina Brown', 'Cuozheqiangma', 0.4);
insert into agents (aname, city, percent) values ('Carlos Willis', 'Oslo', 0.44);
insert into agents (aname, city, percent) values ('Ronald Lynch', 'Wilamowice', 0.54);
insert into agents (aname, city, percent) values ('Nicole Russell', 'Ciechocin', 0.99);
insert into agents (aname, city, percent) values ('Craig Chapman', 'Tawun', 0.17);
insert into agents (aname, city, percent) values ('Carolyn Bennett', 'Langue', 0.17);
insert into agents (aname, city, percent) values ('Pamela Hansen', 'Kampong Chhnang', 0.09);
insert into agents (aname, city, percent) values ('Bruce Wallace', 'Shuiquan', 0.2);
insert into agents (aname, city, percent) values ('Anna Howell', 'Järfälla', 0.92);
insert into agents (aname, city, percent) values ('Nicole Marshall', 'Bandjoun', 0.48);
insert into agents (aname, city, percent) values ('Paul Greene', 'Dresden', 0.23);
insert into agents (aname, city, percent) values ('Kimberly Wright', 'Nhơn Trạch', 0.15);
insert into agents (aname, city, percent) values ('Katherine Garrett', 'Torkanivka', 0.07);
insert into agents (aname, city, percent) values ('Theresa Morgan', 'Shantou', 0.83);
insert into agents (aname, city, percent) values ('Anne Hansen', 'Natarleba', 0.87);
insert into agents (aname, city, percent) values ('Phillip Warren', 'Vilhena', 0.44);
insert into agents (aname, city, percent) values ('Margaret Jackson', 'Amiens', 0.51);
insert into agents (aname, city, percent) values ('Bonnie Scott', 'Divinópolis', 0.88);
insert into agents (aname, city, percent) values ('Kevin Rice', 'Jiangcun', 0.16);
insert into agents (aname, city, percent) values ('Kimberly Kennedy', 'La Paz', 0.98);
insert into agents (aname, city, percent) values ('Joe Bryant', 'As Samawah', 0.38);
insert into agents (aname, city, percent) values ('Terry Ortiz', 'Makīnsk', 0.66);
insert into agents (aname, city, percent) values ('Wanda Richards', 'Ailibugai', 0.66);
insert into agents (aname, city, percent) values ('Martin Dean', 'Duru', 0.48);
insert into agents (aname, city, percent) values ('Tina Graham', 'Żabno', 0.6);
insert into agents (aname, city, percent) values ('Andrea Porter', 'Raszków', 0.69);
insert into agents (aname, city, percent) values ('Rose Grant', 'Piancheng', 0.23);
insert into agents (aname, city, percent) values ('Dennis Fuller', 'Lamakera Dua', 0.01);
insert into agents (aname, city, percent) values ('Kimberly Cook', 'Rasūlnagar', 0.41);
insert into agents (aname, city, percent) values ('Sandra Snyder', 'Bertioga', 1.0);
insert into agents (aname, city, percent) values ('Michelle Harvey', 'Santo Amador', 0.56);
insert into agents (aname, city, percent) values ('Kathy King', 'Hamilton', 0.67);
insert into agents (aname, city, percent) values ('Jesse Harvey', 'Eldama Ravine', 0.07);
insert into agents (aname, city, percent) values ('Julia Rose', 'Ussuriysk', 0.3);
insert into agents (aname, city, percent) values ('Teresa Mcdonald', 'Xiatuanpu', 0.51);
insert into agents (aname, city, percent) values ('Kelly Flores', 'Pukë', 0.12);
insert into agents (aname, city, percent) values ('Jean Reid', 'Zhaoguli', 0.53);
insert into agents (aname, city, percent) values ('Jack Romero', 'Tigpalay', 0.56);
insert into agents (aname, city, percent) values ('Clarence Foster', 'Ugep', 0.18);
insert into agents (aname, city, percent) values ('Frank Harper', 'Giado', 0.32);
insert into agents (aname, city, percent) values ('Annie Morrison', 'Sukamaju', 0.9);
insert into agents (aname, city, percent) values ('Charles Peters', 'Lazi', 0.51);
insert into agents (aname, city, percent) values ('Shirley Hill', 'Içara', 0.7);
insert into agents (aname, city, percent) values ('Harold Mason', 'Delmas', 0.33);
insert into agents (aname, city, percent) values ('Timothy Andrews', 'Ngurore', 0.96);
insert into agents (aname, city, percent) values ('Sara Hansen', 'Limbuš', 0.36);
insert into agents (aname, city, percent) values ('Katherine Thomas', 'Paatan', 0.61);
insert into agents (aname, city, percent) values ('Doris Meyer', 'Jiangzao', 0.43);
insert into agents (aname, city, percent) values ('Janice Perez', 'Jevremovac', 0.87);
insert into agents (aname, city, percent) values ('Beverly Marshall', 'Baćkowice', 0.2);
insert into agents (aname, city, percent) values ('Anne Gomez', 'Rovnoye', 0.16);
insert into agents (aname, city, percent) values ('Rebecca Grant', 'Baturinggit Kaja', 0.39);
insert into agents (aname, city, percent) values ('Anna Bishop', 'Marka', 0.2);
insert into agents (aname, city, percent) values ('Ashley Vasquez', 'Senneterre', 0.78);
insert into agents (aname, city, percent) values ('Amanda Phillips', 'Ukrainka', 0.11);
insert into agents (aname, city, percent) values ('Marilyn Garcia', 'Kyankwanzi', 0.9);
insert into agents (aname, city, percent) values ('Ashley Smith', 'Weixing', 0.58);
insert into agents (aname, city, percent) values ('Dennis Campbell', 'Dalongtan', 0.89);
insert into agents (aname, city, percent) values ('Judy Moore', 'Nazir Town', 0.16);
insert into agents (aname, city, percent) values ('Peter Kelly', 'Resapombo', 0.01);
insert into agents (aname, city, percent) values ('Alice Murray', 'Halat', 0.22);
insert into agents (aname, city, percent) values ('Anne Stanley', 'Iwai', 0.7);
insert into agents (aname, city, percent) values ('Paul Simmons', 'Mosteiros', 0.52);
insert into agents (aname, city, percent) values ('Michael Taylor', 'Donabate', 0.6);
insert into agents (aname, city, percent) values ('Ruby Lee', 'Bweyogerere', 0.02);
insert into agents (aname, city, percent) values ('Roger Miller', 'Abucay', 0.9);
insert into agents (aname, city, percent) values ('Nicholas Johnson', 'Arroio Grande', 0.9);
insert into agents (aname, city, percent) values ('Elizabeth Griffin', 'Tempeh Tengah', 0.71);
insert into agents (aname, city, percent) values ('Betty Lee', 'Lidong', 0.9);
insert into agents (aname, city, percent) values ('Kenneth Peterson', 'Paris 08', 0.49);
insert into agents (aname, city, percent) values ('Jennifer Stanley', 'Las Piñas', 0.38);
insert into agents (aname, city, percent) values ('Andrea Robinson', 'Yidu', 0.26);
insert into agents (aname, city, percent) values ('Joseph Lawson', 'Mikun’', 0.99);
insert into agents (aname, city, percent) values ('Julie Lewis', 'Carreira', 0.06);
insert into agents (aname, city, percent) values ('Margaret Murphy', 'Okanagan', 0.45);
insert into agents (aname, city, percent) values ('Ashley Ruiz', 'Donji Vakuf', 0.02);
insert into agents (aname, city, percent) values ('Billy Oliver', 'Swan Hills', 0.48);
insert into agents (aname, city, percent) values ('Joshua Bennett', 'Myrnyy', 0.33);
insert into agents (aname, city, percent) values ('Todd Hall', 'Naples', 0.31);
insert into agents (aname, city, percent) values ('Gary Kennedy', 'Rybnoye', 0.88);
insert into agents (aname, city, percent) values ('Eric Grant', 'Hejiaping', 0.97);
insert into agents (aname, city, percent) values ('Brian Hall', 'Krajan Langenharjo', 0.87);
insert into agents (aname, city, percent) values ('Maria Chavez', 'Omaha', 0.44);
insert into agents (aname, city, percent) values ('Harry Reynolds', 'Yugang', 0.93);
insert into agents (aname, city, percent) values ('Justin Hamilton', 'San Pa Tong', 0.86);
insert into agents (aname, city, percent) values ('Thomas Collins', 'Saransk', 0.39);
insert into agents (aname, city, percent) values ('Antonio Reynolds', 'Tangfang', 0.47);
insert into agents (aname, city, percent) values ('Ashley Cooper', 'Huacho', 0.27);
insert into agents (aname, city, percent) values ('Beverly Wilson', 'Ōsaka-shi', 0.28);
insert into agents (aname, city, percent) values ('Christopher Larson', 'Chiclayo', 0.52);
insert into agents (aname, city, percent) values ('Donna Lawson', 'Acacías', 0.94);
insert into agents (aname, city, percent) values ('Arthur Collins', 'Punta Cana', 0.81);
insert into agents (aname, city, percent) values ('Deborah Nichols', 'Shangxian', 0.48);
insert into agents (aname, city, percent) values ('Jean Nichols', 'Zhentou', 0.53);
insert into agents (aname, city, percent) values ('Fred Elliott', 'Conroe', 0.65);
insert into agents (aname, city, percent) values ('Scott Owens', 'Bieniewice', 0.74);
insert into agents (aname, city, percent) values ('Randy Thompson', 'Eusébio', 0.93);
insert into agents (aname, city, percent) values ('Justin Matthews', 'Svorónos', 0.54);
insert into agents (aname, city, percent) values ('Adam Hill', 'Wilkowice', 0.88);
insert into agents (aname, city, percent) values ('Earl Carr', 'Hot', 0.86);
insert into agents (aname, city, percent) values ('Carol Garza', 'Wangge’ertang', 0.95);
insert into agents (aname, city, percent) values ('Scott Miller', 'Birmingham', 0.07);
insert into agents (aname, city, percent) values ('Lawrence Howell', 'Chervone', 0.18);
insert into agents (aname, city, percent) values ('Aaron Meyer', 'Progreso', 0.98);
insert into agents (aname, city, percent) values ('Rebecca Burke', 'Yashiro', 0.87);
insert into agents (aname, city, percent) values ('Mary Stanley', 'Xaçmaz', 0.75);
insert into agents (aname, city, percent) values ('Randy Richardson', 'Bakadagy', 0.61);
insert into agents (aname, city, percent) values ('Anna Moore', 'Cordon', 0.03);
insert into agents (aname, city, percent) values ('Harry Gibson', 'Embu', 0.98);
insert into agents (aname, city, percent) values ('Walter Nelson', 'Pavlogradka', 0.45);
insert into agents (aname, city, percent) values ('Laura Bradley', 'Chaumont', 0.32);
insert into agents (aname, city, percent) values ('Shirley Bryant', 'Aranyaprathet', 0.41);
insert into agents (aname, city, percent) values ('Ronald Olson', 'Cassilândia', 0.29);
insert into agents (aname, city, percent) values ('Dennis Arnold', 'Wuyang', 0.71);
insert into agents (aname, city, percent) values ('Pamela Wheeler', 'Huineno', 0.5);
insert into agents (aname, city, percent) values ('Katherine Gilbert', 'Ternate', 1.0);
insert into agents (aname, city, percent) values ('Michael Shaw', 'Zhijiang', 0.12);
insert into agents (aname, city, percent) values ('Louise Stanley', 'Florida', 0.66);
insert into agents (aname, city, percent) values ('Ruby Bennett', 'Hanjia', 0.13);
insert into agents (aname, city, percent) values ('Susan White', 'Al ‘Anān', 0.7);
insert into agents (aname, city, percent) values ('Gary Ward', 'Sieroszewice', 0.91);
insert into agents (aname, city, percent) values ('Nancy Riley', 'Liboro', 0.92);
insert into agents (aname, city, percent) values ('Bonnie Barnes', 'Paterson', 0.38);
insert into agents (aname, city, percent) values ('Gary Wallace', 'São Tomé', 0.35);
insert into agents (aname, city, percent) values ('Alan Gomez', 'Washington', 0.91);
insert into agents (aname, city, percent) values ('Wayne Olson', 'Monte Branco', 0.74);
insert into agents (aname, city, percent) values ('Timothy Hernandez', 'Cungking', 0.25);
insert into agents (aname, city, percent) values ('Kevin Cook', 'Sekondi-Takoradi', 0.69);
insert into agents (aname, city, percent) values ('Ryan Ryan', 'Jakubowice Murowane', 0.11);
insert into agents (aname, city, percent) values ('Earl Williamson', 'Independencia', 0.97);
insert into agents (aname, city, percent) values ('Nancy Cooper', 'Ayní', 0.59);
insert into agents (aname, city, percent) values ('Joseph Hart', 'Oslo', 0.03);
insert into agents (aname, city, percent) values ('Annie Lynch', 'Dongtian', 0.25);
insert into agents (aname, city, percent) values ('Juan Burton', 'Summerside', 0.95);
insert into agents (aname, city, percent) values ('Jason Morales', 'Jiguaní', 0.39);
insert into agents (aname, city, percent) values ('Virginia Harris', 'Were', 0.92);
insert into agents (aname, city, percent) values ('Donna Kelly', 'Foz Giraldo', 0.66);
insert into agents (aname, city, percent) values ('Sara Sullivan', 'Hongqi', 0.11);
insert into agents (aname, city, percent) values ('Johnny Snyder', 'Tignoan', 0.47);
insert into agents (aname, city, percent) values ('Carlos Williamson', 'Gavião', 1.0);
insert into agents (aname, city, percent) values ('Jesse Ford', 'San Buenaventura', 0.15);
insert into agents (aname, city, percent) values ('Russell Burns', 'Patsi', 0.61);
insert into agents (aname, city, percent) values ('Ernest Gilbert', 'Ciheras', 0.61);
insert into agents (aname, city, percent) values ('Gloria Collins', 'Chaplygin', 0.78);
insert into agents (aname, city, percent) values ('Phyllis Mills', 'Aniso', 0.78);
insert into agents (aname, city, percent) values ('Terry Cook', 'Pavlovka', 0.73);
insert into agents (aname, city, percent) values ('Linda Kennedy', 'Guayabetal', 0.02);
insert into agents (aname, city, percent) values ('Thomas Henderson', 'Artsvaberd', 0.05);
insert into agents (aname, city, percent) values ('Christina Murphy', 'Inderka', 0.71);
insert into agents (aname, city, percent) values ('Carolyn Brown', 'Poiares', 0.32);
insert into agents (aname, city, percent) values ('Robert Robertson', 'Fenghua', 0.33);
insert into agents (aname, city, percent) values ('Anna Little', 'Nóvita', 0.74);
insert into agents (aname, city, percent) values ('Wayne Hamilton', 'Banjarjo', 0.19);
insert into agents (aname, city, percent) values ('Antonio Hicks', 'Kieta', 0.84);
insert into agents (aname, city, percent) values ('Janet Long', 'Rakvere', 0.1);
insert into agents (aname, city, percent) values ('Larry Johnston', 'Grenoble', 0.53);
insert into agents (aname, city, percent) values ('James Lynch', 'Smach Mean Chey', 0.49);
insert into agents (aname, city, percent) values ('Robin Shaw', 'Montauban', 0.28);
insert into agents (aname, city, percent) values ('Diane Harper', 'Épernay', 0.75);
insert into agents (aname, city, percent) values ('Jason Austin', 'Kamal', 0.19);
insert into agents (aname, city, percent) values ('Daniel Robinson', 'Marmande', 1.0);
insert into agents (aname, city, percent) values ('Rachel Wright', 'Minas', 0.49);
insert into agents (aname, city, percent) values ('Charles Woods', 'Dao', 0.76);
insert into agents (aname, city, percent) values ('Terry Miller', 'Azogues', 0.9);
insert into agents (aname, city, percent) values ('Michelle Elliott', 'San Pedro Jocopilas', 0.21);
insert into agents (aname, city, percent) values ('Chris Porter', 'Shijiang', 0.75);
insert into agents (aname, city, percent) values ('Charles Simmons', 'Khāngāh Dogrān', 0.26);
insert into agents (aname, city, percent) values ('Christine Bailey', 'San Antonio', 0.19);
insert into agents (aname, city, percent) values ('Cynthia Carroll', 'Villeneuve-la-Garenne', 0.55);
insert into agents (aname, city, percent) values ('Heather Cruz', 'Grybów', 0.61);
insert into agents (aname, city, percent) values ('Amanda Greene', 'Mariental', 0.85);
insert into agents (aname, city, percent) values ('Kathy Payne', 'Krapina', 0.94);
insert into agents (aname, city, percent) values ('Kathryn Gonzalez', 'Libas', 0.03);
insert into agents (aname, city, percent) values ('Nancy Mitchell', 'Rego de Água', 0.37);
insert into agents (aname, city, percent) values ('Julia Ford', 'Dobje pri Planini', 0.22);
insert into agents (aname, city, percent) values ('Gregory Dean', 'Magallanes', 0.44);
insert into agents (aname, city, percent) values ('Anthony Ferguson', 'Portão', 0.86);
insert into agents (aname, city, percent) values ('Patrick Ford', 'Colima', 0.55);
insert into agents (aname, city, percent) values ('Antonio Garza', 'Pare', 0.95);
insert into agents (aname, city, percent) values ('Carlos Chapman', 'Sanankerto', 0.1);
insert into agents (aname, city, percent) values ('Andrew Gibson', 'Zürich', 0.47);
insert into agents (aname, city, percent) values ('Jonathan Larson', 'Krajandadapmulyo', 0.29);
insert into agents (aname, city, percent) values ('Julia Ferguson', 'Yicheng', 0.94);
insert into agents (aname, city, percent) values ('Billy Matthews', '‘Anjarah', 0.4);
insert into agents (aname, city, percent) values ('Jesse Bishop', 'Vizal San Pablo', 0.76);
insert into agents (aname, city, percent) values ('Raymond Harper', 'Wuxing', 0.44);
insert into agents (aname, city, percent) values ('Stephen Greene', 'Aldeia da Piedade', 0.25);
insert into agents (aname, city, percent) values ('Cheryl Schmidt', 'Borås', 0.6);
insert into agents (aname, city, percent) values ('Shawn Jackson', 'Stockholm', 0.99);
insert into agents (aname, city, percent) values ('Martin Richardson', 'Yangdi', 0.66);
insert into agents (aname, city, percent) values ('Bruce Mcdonald', 'Protvino', 0.59);
insert into agents (aname, city, percent) values ('Ralph Black', 'Laocheng', 0.36);
insert into agents (aname, city, percent) values ('Howard Myers', 'Sinamar', 0.57);
insert into agents (aname, city, percent) values ('Rebecca Rivera', 'Belfort', 0.74);
insert into agents (aname, city, percent) values ('Lois James', 'Shilovo', 0.73);
insert into agents (aname, city, percent) values ('Heather Brooks', 'Richibucto', 0.04);
insert into agents (aname, city, percent) values ('Harry Campbell', 'Nerekhta', 0.77);
insert into agents (aname, city, percent) values ('Clarence Duncan', 'Miskolc', 0.94);
insert into agents (aname, city, percent) values ('Jesse Morrison', 'Huxi', 0.67);
insert into agents (aname, city, percent) values ('Gary Williams', 'Kompóti', 0.18);
insert into agents (aname, city, percent) values ('Susan Sanders', 'Shijiao', 0.63);
insert into agents (aname, city, percent) values ('Jason Peterson', 'Dadianzi', 0.97);
insert into agents (aname, city, percent) values ('Arthur Bryant', 'Apuri', 0.41);
insert into agents (aname, city, percent) values ('Jose Reynolds', 'San Pedro del Paraná', 0.58);
insert into agents (aname, city, percent) values ('Rebecca Medina', 'Pajić Polje', 0.42);
insert into agents (aname, city, percent) values ('Jeffrey Diaz', 'Koungou', 0.6);
insert into agents (aname, city, percent) values ('Angela Chapman', 'Hualin', 0.84);
insert into agents (aname, city, percent) values ('Christopher Patterson', 'Jiangpan', 0.0);
insert into agents (aname, city, percent) values ('Arthur Boyd', 'Sjöbo', 0.86);
insert into agents (aname, city, percent) values ('Scott Spencer', 'Mirovka', 0.57);
insert into agents (aname, city, percent) values ('Jason Morgan', 'Bus’k', 0.55);
insert into agents (aname, city, percent) values ('Jose Mendoza', 'Brusy', 0.49);
insert into agents (aname, city, percent) values ('Melissa Lynch', 'Bununu Dass', 0.45);
insert into agents (aname, city, percent) values ('Craig Rogers', 'Ban Mai', 0.61);
insert into agents (aname, city, percent) values ('Melissa Clark', 'Čeladná', 0.53);
insert into agents (aname, city, percent) values ('Wanda Richardson', 'Bonabéri', 0.43);
insert into agents (aname, city, percent) values ('Betty Hudson', 'Pembroke', 0.94);
insert into agents (aname, city, percent) values ('Christine Dunn', 'Zhongyuan', 0.75);
insert into agents (aname, city, percent) values ('Joan Stevens', 'Jiuhua', 0.54);
insert into agents (aname, city, percent) values ('Ruth Arnold', 'Targowisko', 0.96);
insert into agents (aname, city, percent) values ('Jimmy Campbell', 'Arsen’yev', 0.48);
insert into agents (aname, city, percent) values ('John Frazier', 'San Lorenzo', 0.15);
insert into agents (aname, city, percent) values ('Justin Bowman', 'Partille', 0.77);
insert into agents (aname, city, percent) values ('Michelle Ramirez', 'Kabare', 0.52);
insert into agents (aname, city, percent) values ('Patricia Elliott', 'Belanting', 0.4);
insert into agents (aname, city, percent) values ('Chris Fields', 'Barranquilla', 0.38);
insert into agents (aname, city, percent) values ('Jane Coleman', 'San Vicente', 0.8);
insert into agents (aname, city, percent) values ('Jimmy Ford', 'Pedra Azul', 0.86);
insert into agents (aname, city, percent) values ('Ronald James', 'Rokiškis', 0.75);
insert into agents (aname, city, percent) values ('Doris Lewis', 'Göteborg', 0.87);
insert into agents (aname, city, percent) values ('Steve Bryant', 'Envigado', 0.35);
insert into agents (aname, city, percent) values ('Edward Griffin', 'Pio Duran', 0.87);
insert into agents (aname, city, percent) values ('Lillian Gardner', 'Terney', 0.7);
insert into agents (aname, city, percent) values ('Todd Turner', 'Cibeureum', 0.26);
insert into agents (aname, city, percent) values ('Robin Dunn', 'Velykyy Klyuchiv', 0.49);
insert into agents (aname, city, percent) values ('Alan Payne', 'Berón de Astrada', 0.22);
insert into agents (aname, city, percent) values ('Martin Garrett', 'Kunów', 0.59);
insert into agents (aname, city, percent) values ('Jesse Kelly', 'Zagórnik', 0.78);
insert into agents (aname, city, percent) values ('Louis Shaw', 'Swiętajno', 0.4);
insert into agents (aname, city, percent) values ('Terry Carter', 'Vardane', 0.43);
insert into agents (aname, city, percent) values ('Ryan Ferguson', 'Huotong', 0.37);
insert into agents (aname, city, percent) values ('Bonnie Lawrence', 'Gora', 0.7);
insert into agents (aname, city, percent) values ('Sharon Butler', 'Waitakere', 0.07);
insert into agents (aname, city, percent) values ('Christopher Larson', 'Ursynów', 0.13);
insert into agents (aname, city, percent) values ('Linda Lynch', 'Elektrėnai', 0.62);
insert into agents (aname, city, percent) values ('Michael Gray', 'Rio Piracicaba', 0.67);
insert into agents (aname, city, percent) values ('Antonio Morgan', 'Thành Phố Uông Bí', 0.04);
insert into agents (aname, city, percent) values ('Nancy George', 'Shensuo', 0.95);
insert into agents (aname, city, percent) values ('Judith Vasquez', 'Tiro', 0.32);
insert into agents (aname, city, percent) values ('Denise Miller', 'Muldersdriseloop', 0.45);
insert into agents (aname, city, percent) values ('Tina Robinson', 'Dayuan', 0.42);
insert into agents (aname, city, percent) values ('Sarah Cunningham', 'Uliastay', 0.02);
insert into agents (aname, city, percent) values ('Donald Ryan', 'Cola', 0.12);
insert into agents (aname, city, percent) values ('Anna Fernandez', 'Vancouver', 0.31);
insert into agents (aname, city, percent) values ('Terry Harper', 'Nyköping', 0.97);
insert into agents (aname, city, percent) values ('Denise Stephens', 'Caxias do Sul', 0.43);
insert into agents (aname, city, percent) values ('Nancy Mitchell', 'Ojiya', 0.66);
insert into agents (aname, city, percent) values ('Stephen Daniels', 'Xiuying', 0.41);
insert into agents (aname, city, percent) values ('Larry Lane', 'Hitiaa', 0.21);
insert into agents (aname, city, percent) values ('Steve Perkins', 'Sorinomo', 0.27);
insert into agents (aname, city, percent) values ('Betty Little', 'Santa Rosa', 0.34);
insert into agents (aname, city, percent) values ('Angela Lynch', 'Dasheng', 0.39);
insert into agents (aname, city, percent) values ('Fred Larson', 'Nong Phai', 0.32);
insert into agents (aname, city, percent) values ('Nicholas Rose', 'Kisesa', 0.1);
insert into agents (aname, city, percent) values ('Jason Lopez', 'Santo Tomás', 0.04);
insert into agents (aname, city, percent) values ('Martin Oliver', 'Calaba', 0.55);
insert into agents (aname, city, percent) values ('Chris Hunter', 'Pingpo', 0.35);
insert into agents (aname, city, percent) values ('Jason Johnson', 'Karakul’', 0.04);
insert into agents (aname, city, percent) values ('Juan Woods', 'Béreldange', 0.58);
insert into agents (aname, city, percent) values ('Ruth Lopez', 'Taman', 0.75);
insert into agents (aname, city, percent) values ('Jason Payne', 'Tilburg', 0.98);
insert into agents (aname, city, percent) values ('Sarah Washington', 'Lupane', 0.66);
insert into agents (aname, city, percent) values ('Craig Foster', 'Santa Rosa', 0.56);
insert into agents (aname, city, percent) values ('Paul Sims', 'Ponyri Vtoryye', 0.67);
insert into agents (aname, city, percent) values ('Jean Gordon', 'Tiguha', 0.05);
insert into agents (aname, city, percent) values ('Eugene Brooks', 'Humaitá', 0.19);
insert into agents (aname, city, percent) values ('Katherine Robinson', 'Sangar Sarāy', 0.87);
insert into agents (aname, city, percent) values ('Susan Thompson', 'Kirkland Lake', 0.49);
insert into agents (aname, city, percent) values ('Theresa Hill', 'Murcia', 0.62);
insert into agents (aname, city, percent) values ('Scott Roberts', 'Paraíso', 0.33);
insert into agents (aname, city, percent) values ('Kathleen Grant', 'Cherëmukhovo', 0.96);
insert into agents (aname, city, percent) values ('Harry Wilson', 'Guaíra', 0.14);
insert into agents (aname, city, percent) values ('Harold Alexander', 'Ikaalinen', 0.81);
insert into agents (aname, city, percent) values ('Bruce Gutierrez', 'Candelaria', 0.61);
insert into agents (aname, city, percent) values ('Ralph Smith', 'Richmond', 0.08);
insert into agents (aname, city, percent) values ('Kevin Hill', 'Feyẕābād', 0.58);
insert into agents (aname, city, percent) values ('Michelle Ryan', 'Souto de Cima', 0.4);
insert into agents (aname, city, percent) values ('Kathleen Cox', 'Wanfang', 0.75);
insert into agents (aname, city, percent) values ('Christina Jones', 'Nawābganj', 0.09);
insert into agents (aname, city, percent) values ('Marie Reyes', 'Benger', 0.36);
insert into agents (aname, city, percent) values ('Heather Garcia', 'Cortiçóis', 0.36);
insert into agents (aname, city, percent) values ('Shirley Nguyen', 'Atyrau', 0.38);
insert into agents (aname, city, percent) values ('Ashley Cole', 'Świecie nad Osą', 0.4);
insert into agents (aname, city, percent) values ('Robert Collins', 'Petrivka', 0.51);
insert into agents (aname, city, percent) values ('Raymond Nguyen', 'Alcoy', 0.03);
insert into agents (aname, city, percent) values ('George Edwards', 'Besançon', 0.81);
insert into agents (aname, city, percent) values ('Cynthia Castillo', 'Sukogunungkrajan', 0.62);
insert into agents (aname, city, percent) values ('Earl Woods', 'Karangdalam', 0.52);
insert into agents (aname, city, percent) values ('Norma Simmons', 'København', 0.99);
insert into agents (aname, city, percent) values ('Sarah Chapman', 'Haizigou', 0.21);
insert into agents (aname, city, percent) values ('Alan Richardson', 'Ōami', 0.72);
insert into agents (aname, city, percent) values ('John Schmidt', 'Wujing', 0.16);
insert into agents (aname, city, percent) values ('Melissa Kim', 'Syców', 0.9);
insert into agents (aname, city, percent) values ('George Robinson', 'Praga Północ', 0.77);
insert into agents (aname, city, percent) values ('Paula Scott', 'Bielawa', 0.45);
insert into agents (aname, city, percent) values ('Earl Daniels', 'Detroit', 0.25);
insert into agents (aname, city, percent) values ('Deborah Graham', 'Qal‘ah-ye Shahr', 0.04);
insert into agents (aname, city, percent) values ('Wayne Rice', 'Gibsons', 0.01);
insert into agents (aname, city, percent) values ('Heather Lewis', 'Noshiro', 0.01);
insert into agents (aname, city, percent) values ('Juan Elliott', 'Tochigi', 0.67);
insert into agents (aname, city, percent) values ('Anna Bowman', 'Jishi', 0.82);
insert into agents (aname, city, percent) values ('Howard Wright', 'Pont-à-Mousson', 0.39);
insert into agents (aname, city, percent) values ('Paula Barnes', 'Brudzeń Duży', 0.39);
insert into agents (aname, city, percent) values ('Shirley Walker', 'Nancy', 0.81);
insert into agents (aname, city, percent) values ('Janice Bryant', 'Siyabuswa', 0.01);
insert into agents (aname, city, percent) values ('Walter Morris', 'Gandapura', 0.2);
insert into agents (aname, city, percent) values ('Lori Harper', 'Ilembula', 0.8);
insert into agents (aname, city, percent) values ('Denise Meyer', 'Cabcaben', 0.17);
insert into agents (aname, city, percent) values ('Diana White', 'Horní Cerekev', 0.38);
insert into agents (aname, city, percent) values ('Cheryl Elliott', 'Kongolo', 0.19);
insert into agents (aname, city, percent) values ('Nancy Sanders', 'Lazaro Cardenas', 0.95);
insert into agents (aname, city, percent) values ('Cheryl Spencer', 'Isfana', 0.3);
insert into agents (aname, city, percent) values ('Christine Montgomery', 'Guali', 0.3);
insert into agents (aname, city, percent) values ('Brian Greene', 'Jinxiu', 0.62);
insert into agents (aname, city, percent) values ('John Kelley', 'Cibunut', 0.28);
insert into agents (aname, city, percent) values ('Ashley Sullivan', 'Barapas', 0.22);
insert into agents (aname, city, percent) values ('Dennis Price', 'Thị Trấn Tam Điệp', 0.43);
insert into agents (aname, city, percent) values ('Henry Roberts', 'North Battleford', 0.55);
insert into agents (aname, city, percent) values ('Juan Peterson', 'Xiying', 0.12);
insert into agents (aname, city, percent) values ('Evelyn Washington', 'Järfälla', 0.23);
insert into agents (aname, city, percent) values ('Louis Woods', 'Georgīevka', 0.23);
insert into agents (aname, city, percent) values ('Emily Evans', 'Vĩnh Tường', 0.65);
insert into agents (aname, city, percent) values ('Sharon Harvey', 'Tanahmerah', 0.8);
insert into agents (aname, city, percent) values ('Kathleen Young', 'Accha', 0.79);
insert into agents (aname, city, percent) values ('Diane Ward', 'Samobor', 0.38);
insert into agents (aname, city, percent) values ('Sharon Gardner', 'Barcin', 0.06);
insert into agents (aname, city, percent) values ('Antonio Hart', 'Baiyun', 0.67);
insert into agents (aname, city, percent) values ('Marilyn Baker', 'Drammen', 0.73);
insert into agents (aname, city, percent) values ('Robin Knight', 'Longhu', 0.2);
insert into agents (aname, city, percent) values ('Robert Myers', 'Peer', 0.9);
insert into agents (aname, city, percent) values ('Jeremy Perez', 'El Cubolero', 0.94);
insert into agents (aname, city, percent) values ('Jesse Mason', 'Capissayan Sur', 0.07);
insert into agents (aname, city, percent) values ('Eric Hayes', 'Abaeté', 0.62);
insert into agents (aname, city, percent) values ('Donna Allen', 'Suwaru', 0.31);
insert into agents (aname, city, percent) values ('Diana Black', 'Munggang', 0.56);
insert into agents (aname, city, percent) values ('Mildred Lawson', 'Dehang', 0.45);
insert into agents (aname, city, percent) values ('Adam Little', 'Vicente Guerrero', 0.39);
insert into agents (aname, city, percent) values ('David Day', 'Zamora', 0.86);
insert into agents (aname, city, percent) values ('Anthony Hill', 'El Tabo', 0.25);
insert into agents (aname, city, percent) values ('Fred Jackson', 'Xihe', 0.36);
insert into agents (aname, city, percent) values ('Edward Palmer', 'Polykárpi', 0.66);
insert into agents (aname, city, percent) values ('Stephanie Lee', 'Pavlohrad', 0.32);
insert into agents (aname, city, percent) values ('Jack Hill', 'Sangoleng', 0.26);
insert into agents (aname, city, percent) values ('Judy Torres', 'Rio das Pedras', 0.67);
insert into agents (aname, city, percent) values ('Clarence Graham', 'Pentre', 0.02);
insert into agents (aname, city, percent) values ('Lois Dunn', 'Erechim', 0.64);
insert into agents (aname, city, percent) values ('Alan Patterson', 'Jiangshan', 0.92);
insert into agents (aname, city, percent) values ('Gregory Henderson', 'Touama', 0.46);
insert into agents (aname, city, percent) values ('Frances Adams', 'La Tebaida', 0.34);
insert into agents (aname, city, percent) values ('Lillian Stewart', 'Bapska', 0.86);
insert into agents (aname, city, percent) values ('Willie Burke', 'Llorente', 0.76);
insert into agents (aname, city, percent) values ('Aaron Schmidt', 'Sanxing', 0.96);
insert into agents (aname, city, percent) values ('Richard Boyd', 'Timurjaya', 0.69);
insert into agents (aname, city, percent) values ('Stephanie Howard', 'Shidong', 0.29);
insert into agents (aname, city, percent) values ('Larry Lopez', 'Fukura', 0.9);
insert into agents (aname, city, percent) values ('Keith Wells', 'Sauce', 0.35);
insert into agents (aname, city, percent) values ('Ashley Garrett', 'Markaz Mudhaykirah', 0.76);
insert into agents (aname, city, percent) values ('Kathleen Turner', 'Hezhang', 0.98);
insert into agents (aname, city, percent) values ('James Burns', 'Puntarenas', 0.48);
insert into agents (aname, city, percent) values ('Shawn Nichols', 'Buinsk', 0.71);
insert into agents (aname, city, percent) values ('Jennifer Rodriguez', 'Prengtale', 0.85);
insert into agents (aname, city, percent) values ('Laura Boyd', 'Beijie', 0.07);
insert into agents (aname, city, percent) values ('Christopher Hicks', 'Aubervilliers', 0.85);
insert into agents (aname, city, percent) values ('Eugene Harper', 'Aku', 0.58);
insert into agents (aname, city, percent) values ('Benjamin Bennett', 'Võhma', 0.99);
insert into agents (aname, city, percent) values ('George Reed', 'Hetoudian', 0.67);
insert into agents (aname, city, percent) values ('Bobby Andrews', 'Khon San', 0.19);
insert into agents (aname, city, percent) values ('Bruce Daniels', 'Jianshan', 0.11);
insert into agents (aname, city, percent) values ('Teresa Grant', 'Bosobolo', 0.25);
insert into agents (aname, city, percent) values ('Stephen Ryan', 'Unaizah', 0.62);
insert into agents (aname, city, percent) values ('Janice Martinez', 'Shizi', 0.97);
insert into agents (aname, city, percent) values ('Emily Tucker', 'Parakanbeusi', 0.31);
insert into agents (aname, city, percent) values ('Anne Fisher', 'Gjirokastër', 0.07);
insert into agents (aname, city, percent) values ('Michael Stone', 'Moriyama', 0.83);
insert into agents (aname, city, percent) values ('Wayne Flores', 'Emmeloord', 0.5);
insert into agents (aname, city, percent) values ('Bonnie Williamson', 'Purranque', 0.98);
insert into agents (aname, city, percent) values ('William Stewart', 'Gersikputih Tengah', 0.1);
insert into agents (aname, city, percent) values ('Alice Washington', 'Diaoling', 0.82);
insert into agents (aname, city, percent) values ('Harold Lewis', 'New Haven', 0.83);
insert into agents (aname, city, percent) values ('Phyllis White', 'Albanel', 0.66);
insert into agents (aname, city, percent) values ('Irene Stewart', 'Huangshi', 0.6);
insert into agents (aname, city, percent) values ('Fred Berry', 'Qinjiang', 0.56);
insert into agents (aname, city, percent) values ('Mary Stevens', 'Maddela', 0.0);
insert into agents (aname, city, percent) values ('Brian Hunt', 'Sérvia', 0.18);
insert into agents (aname, city, percent) values ('Rebecca Burns', 'Kasingan', 0.92);
insert into agents (aname, city, percent) values ('Joan Gonzalez', 'Sungai', 0.94);
insert into agents (aname, city, percent) values ('Alice Ford', 'Man', 0.08);
insert into agents (aname, city, percent) values ('Kevin Burke', 'Sovetskaya', 0.52);
insert into agents (aname, city, percent) values ('Walter Graham', 'Quilino', 0.76);
insert into agents (aname, city, percent) values ('Katherine Mills', 'Tagoloan', 0.3);
insert into agents (aname, city, percent) values ('Randy Boyd', 'Manjakandriana', 0.55);
insert into agents (aname, city, percent) values ('Christopher Russell', 'Ilama', 0.6);
insert into agents (aname, city, percent) values ('Carl Reyes', 'Los Angeles', 0.31);
insert into agents (aname, city, percent) values ('Kelly Mason', 'Juren', 0.78);
insert into agents (aname, city, percent) values ('Marilyn Pierce', 'Łęknica', 0.32);
insert into agents (aname, city, percent) values ('Todd Holmes', 'Veles', 0.95);
insert into agents (aname, city, percent) values ('Kathleen Andrews', 'Sumiainen', 0.43);
insert into agents (aname, city, percent) values ('Pamela Thomas', 'Lower Hutt', 0.89);
insert into agents (aname, city, percent) values ('Eugene Palmer', 'Adir', 0.52);
insert into agents (aname, city, percent) values ('Margaret Bailey', 'Rentian', 0.12);
insert into agents (aname, city, percent) values ('Charles Daniels', 'San Nicolas', 0.33);
insert into agents (aname, city, percent) values ('Jack Robinson', 'Zahedan', 0.49);
insert into agents (aname, city, percent) values ('Russell Foster', 'Pashkovskiy', 0.33);
insert into agents (aname, city, percent) values ('Stephen James', 'Ngrejo', 0.52);
insert into agents (aname, city, percent) values ('Jesse Hansen', 'Kauhan', 0.58);
insert into agents (aname, city, percent) values ('Johnny Fisher', 'Moate', 0.76);
insert into agents (aname, city, percent) values ('Edward Arnold', 'Sairam', 0.7);
insert into agents (aname, city, percent) values ('Douglas Robinson', 'Limonade', 0.53);
insert into agents (aname, city, percent) values ('Jonathan Cunningham', 'Vannes', 0.4);
insert into agents (aname, city, percent) values ('Richard Myers', 'Gāvbandī', 0.83);
insert into agents (aname, city, percent) values ('Eugene Bennett', 'Péplos', 0.72);
insert into agents (aname, city, percent) values ('Paul Roberts', 'Chengdu', 0.48);
insert into agents (aname, city, percent) values ('Carolyn Riley', 'Ceadîr-Lunga', 0.23);
insert into agents (aname, city, percent) values ('Ryan Watkins', 'Priupskiy', 0.14);
insert into agents (aname, city, percent) values ('Marie Morris', 'Chabařovice', 0.84);
insert into agents (aname, city, percent) values ('Harold Mitchell', 'São Pedro Gafanhoeira', 0.66);
insert into agents (aname, city, percent) values ('Joe Kennedy', 'Bürenhayrhan', 0.95);
insert into agents (aname, city, percent) values ('Jessica Bowman', 'Abbotsford', 0.97);
insert into agents (aname, city, percent) values ('Debra Graham', 'Dowan', 0.62);
insert into agents (aname, city, percent) values ('Lois Murphy', 'Bulawayo', 0.14);
insert into agents (aname, city, percent) values ('Christopher Wood', 'Buenavista', 0.49);
insert into agents (aname, city, percent) values ('Martha Banks', 'Biting', 0.78);
insert into agents (aname, city, percent) values ('Jacqueline Butler', 'Markova', 0.76);
insert into agents (aname, city, percent) values ('Arthur Carr', 'Chalcos', 0.33);
insert into agents (aname, city, percent) values ('Kevin Edwards', 'Ketapang', 0.48);
insert into agents (aname, city, percent) values ('Christine Hudson', 'Kanshan', 0.22);
insert into agents (aname, city, percent) values ('William Campbell', 'Rakek', 0.31);
insert into agents (aname, city, percent) values ('Steve James', 'Shangyi', 0.18);
insert into agents (aname, city, percent) values ('Sarah Rose', 'Gaoqiao', 0.91);
insert into agents (aname, city, percent) values ('Russell Carpenter', 'Ganding', 0.85);
insert into agents (aname, city, percent) values ('Justin Ramirez', 'Javhlant', 0.5);
insert into agents (aname, city, percent) values ('Janice Johnson', 'Shangxing', 0.21);
insert into agents (aname, city, percent) values ('Nancy Hill', 'Yuguan', 0.95);
insert into agents (aname, city, percent) values ('Dorothy Willis', 'Patquía', 0.39);
insert into agents (aname, city, percent) values ('Anthony Stephens', 'Troitsk', 0.75);
insert into agents (aname, city, percent) values ('Alan Brooks', 'Guisa', 0.79);
insert into agents (aname, city, percent) values ('Raymond Wagner', 'Västerhaninge', 0.25);
insert into agents (aname, city, percent) values ('Larry Daniels', 'Verkhniye Kigi', 0.48);
insert into agents (aname, city, percent) values ('Fred Montgomery', 'Argenteuil', 0.79);
insert into agents (aname, city, percent) values ('Julie Smith', 'Castle Bruce', 0.94);
insert into agents (aname, city, percent) values ('Ronald Arnold', 'Ağdam', 0.86);
insert into agents (aname, city, percent) values ('Judy Kelley', 'Čakovec', 0.41);
insert into agents (aname, city, percent) values ('Carolyn Williamson', 'Thị Trấn Ngan Dừa', 0.01);
insert into agents (aname, city, percent) values ('Louise Rogers', 'Aconibe', 0.64);
insert into agents (aname, city, percent) values ('Rebecca Ross', 'Spring', 0.65);
insert into agents (aname, city, percent) values ('Roger Frazier', 'Businga', 0.57);
insert into agents (aname, city, percent) values ('Rose Wells', 'Shaoha', 1.0);
insert into agents (aname, city, percent) values ('Phyllis Carroll', 'Götene', 0.65);
insert into agents (aname, city, percent) values ('Martha Howell', 'Coromoro', 0.73);
insert into agents (aname, city, percent) values ('Randy Fuller', 'Ashkāsham', 0.05);
insert into agents (aname, city, percent) values ('Gregory Harrison', 'San Patricio', 0.12);
insert into agents (aname, city, percent) values ('Alice Hernandez', 'Acherítou', 0.47);
insert into agents (aname, city, percent) values ('Ann Miller', 'Bol’shoy Kamen’', 0.99);
insert into agents (aname, city, percent) values ('Raymond Turner', 'Maungatapere', 0.63);
insert into agents (aname, city, percent) values ('Carol Montgomery', 'Bykov', 0.43);
insert into agents (aname, city, percent) values ('Anne Peters', 'Ciulu', 0.96);
insert into agents (aname, city, percent) values ('Tammy Woods', 'Voronezh', 0.32);
insert into agents (aname, city, percent) values ('Theresa Ellis', 'Ljungby', 0.07);
insert into agents (aname, city, percent) values ('Roy Butler', 'Stockholm', 0.25);
insert into agents (aname, city, percent) values ('Ernest Harper', 'Nailung', 0.44);
insert into agents (aname, city, percent) values ('Earl Howard', 'Hyrynsalmi', 0.71);
insert into agents (aname, city, percent) values ('Carolyn Schmidt', 'Auna', 0.21);
insert into agents (aname, city, percent) values ('Ruth Day', 'Mairana', 0.52);
insert into agents (aname, city, percent) values ('Paula Carroll', 'Meruge', 0.87);
insert into agents (aname, city, percent) values ('Willie Howell', 'Tessaoua', 0.03);
insert into agents (aname, city, percent) values ('Janet Morrison', 'Xinbu', 0.96);
insert into agents (aname, city, percent) values ('Diana Gardner', 'Usquil', 0.54);
insert into agents (aname, city, percent) values ('John Simmons', 'Viterbo', 0.13);
insert into agents (aname, city, percent) values ('Randy Hicks', 'Zarzal', 0.65);
insert into agents (aname, city, percent) values ('Judy Torres', 'Svoboda nad Úpou', 0.67);
insert into agents (aname, city, percent) values ('Michelle Watson', 'Viking', 0.66);
insert into agents (aname, city, percent) values ('Adam Kelly', 'Osasco', 0.97);
insert into agents (aname, city, percent) values ('Patricia Ryan', 'São Bernardo do Campo', 0.05);
insert into agents (aname, city, percent) values ('Samuel Gonzalez', 'Węgliniec', 0.13);
insert into agents (aname, city, percent) values ('Roger Larson', 'Erenhot', 0.52);
insert into agents (aname, city, percent) values ('Sarah Foster', 'Solnice', 0.67);
insert into agents (aname, city, percent) values ('Julie Martinez', 'Vanimo', 0.68);
insert into agents (aname, city, percent) values ('Nicholas Armstrong', 'Ilongero', 0.61);
insert into agents (aname, city, percent) values ('Roger Howell', 'Sidomekar', 0.19);
insert into agents (aname, city, percent) values ('Christine Cook', 'Huatajata', 0.34);
insert into agents (aname, city, percent) values ('Amanda Mason', 'Paris 12', 0.5);
insert into agents (aname, city, percent) values ('Annie Graham', 'Broska', 0.74);
insert into agents (aname, city, percent) values ('Antonio Schmidt', 'Lazaro Cardenas', 0.05);
insert into agents (aname, city, percent) values ('Gerald Holmes', 'Akaki', 0.3);
insert into agents (aname, city, percent) values ('Evelyn Spencer', 'Mayo', 0.45);
insert into agents (aname, city, percent) values ('John Adams', 'Brokopondo', 0.49);
insert into agents (aname, city, percent) values ('Alan Daniels', 'Yantian', 0.58);
insert into agents (aname, city, percent) values ('Debra Medina', 'Ketampak', 0.78);
insert into agents (aname, city, percent) values ('Joan Willis', 'Klapagada', 0.44);
insert into agents (aname, city, percent) values ('Doris Romero', 'Xingfu', 0.26);
insert into agents (aname, city, percent) values ('Ashley Richards', 'Bafoussam', 0.37);
insert into agents (aname, city, percent) values ('Wayne Robinson', 'Oullins', 0.91);
insert into agents (aname, city, percent) values ('Justin Washington', 'Al Maḩfid', 0.78);
insert into agents (aname, city, percent) values ('Jonathan West', 'Eirado', 0.9);
insert into agents (aname, city, percent) values ('Marilyn Rogers', 'Seattle', 0.47);
insert into agents (aname, city, percent) values ('Patrick Freeman', 'Kumlinge', 0.53);
insert into agents (aname, city, percent) values ('Donald Fox', 'Tiberias', 0.75);
insert into agents (aname, city, percent) values ('Benjamin Armstrong', 'Nōgata', 0.52);
insert into agents (aname, city, percent) values ('Carol Stanley', 'Cahuac', 0.35);
insert into agents (aname, city, percent) values ('Joan Anderson', 'Yangyuan', 0.34);
insert into agents (aname, city, percent) values ('Brandon Carr', 'Mégara', 0.16);
insert into agents (aname, city, percent) values ('James Sanchez', 'La Soledad', 0.66);
insert into agents (aname, city, percent) values ('Lori Burns', 'Bang Phae', 0.65);
insert into agents (aname, city, percent) values ('Joshua Ward', 'Arcueil', 0.3);
insert into agents (aname, city, percent) values ('Jeremy Kim', 'Dorowa Mining Lease', 0.08);
insert into agents (aname, city, percent) values ('Lillian Cox', 'Kakata', 0.15);
insert into agents (aname, city, percent) values ('Louis Hernandez', 'Sadang Kulon', 0.43);
insert into agents (aname, city, percent) values ('Philip Morales', 'Krasica', 0.9);
insert into agents (aname, city, percent) values ('Joyce Allen', 'Hetian', 0.18);
insert into agents (aname, city, percent) values ('Norma Meyer', 'Xiluo', 0.59);
insert into agents (aname, city, percent) values ('Bruce Nelson', 'Ambatolaona', 0.67);
insert into agents (aname, city, percent) values ('Rebecca Rivera', 'Hongos', 0.02);
insert into agents (aname, city, percent) values ('Harry Gordon', 'Maïné Soroa', 0.95);
insert into agents (aname, city, percent) values ('Joyce Jones', 'Shalang', 0.64);
insert into agents (aname, city, percent) values ('Roger Cunningham', 'Stord', 0.18);
insert into agents (aname, city, percent) values ('Martha Wagner', 'Kobleve', 0.68);
insert into agents (aname, city, percent) values ('Rebecca Hart', 'Ngawen', 0.33);
insert into agents (aname, city, percent) values ('Johnny Butler', 'Bené Beraq', 0.37);
insert into agents (aname, city, percent) values ('Bruce Evans', 'Liboro', 0.69);
insert into agents (aname, city, percent) values ('Philip Stephens', 'Basista', 0.59);
insert into agents (aname, city, percent) values ('Richard Wheeler', 'Ресен', 0.69);
insert into agents (aname, city, percent) values ('Jeffrey Rose', 'Nangalisan', 0.73);
insert into agents (aname, city, percent) values ('Richard Rice', 'Noisy-le-Grand', 0.19);
insert into agents (aname, city, percent) values ('Keith Gibson', 'Hitura', 0.14);
insert into agents (aname, city, percent) values ('Robin Mason', 'Atlanta', 0.82);
insert into agents (aname, city, percent) values ('Carlos Kelley', 'Shuikou', 0.65);
insert into agents (aname, city, percent) values ('Carol Sanchez', 'Stráž nad Nisou', 0.66);
insert into agents (aname, city, percent) values ('Maria Dunn', 'Shangxian', 0.89);
insert into agents (aname, city, percent) values ('Jeremy Carpenter', 'Guimbal', 0.08);
insert into agents (aname, city, percent) values ('Donald Hunter', 'Loshnitsa', 0.98);
insert into agents (aname, city, percent) values ('Teresa Ortiz', 'Koski Tl', 0.34);
insert into agents (aname, city, percent) values ('Antonio Grant', 'Shimen', 0.87);
insert into agents (aname, city, percent) values ('Evelyn Edwards', 'Hrazdan', 0.2);
insert into agents (aname, city, percent) values ('Alan Burke', 'New York City', 0.24);
insert into agents (aname, city, percent) values ('Patrick Ruiz', 'Dipayal', 0.06);
insert into agents (aname, city, percent) values ('Roger Mcdonald', 'Biruinţa', 0.41);
insert into agents (aname, city, percent) values ('Marilyn Grant', 'Xipu', 0.73);
insert into agents (aname, city, percent) values ('Ruth Duncan', 'Vysokovsk', 0.96);
insert into agents (aname, city, percent) values ('Jerry Morris', 'Pokrovo-Prigorodnoye', 0.43);
insert into agents (aname, city, percent) values ('Tina Harper', 'Kamieniec Ząbkowicki', 0.38);
insert into agents (aname, city, percent) values ('Sandra Mendoza', 'Tsivil’sk', 0.52);
insert into agents (aname, city, percent) values ('Deborah Dean', 'Nagahama', 0.77);
insert into agents (aname, city, percent) values ('Kathy Baker', 'Ulaanbaatar', 0.63);
insert into agents (aname, city, percent) values ('Joe Boyd', 'Ogawa', 0.32);
insert into agents (aname, city, percent) values ('James Kim', 'Kamba', 0.53);
insert into agents (aname, city, percent) values ('Jerry Carr', 'Zambujal', 0.17);
insert into agents (aname, city, percent) values ('Jennifer Taylor', 'Agriá', 0.87);
insert into agents (aname, city, percent) values ('Timothy Miller', 'Bandar Pusat Jengka', 0.55);
insert into agents (aname, city, percent) values ('Stephen White', 'Shchelkovo', 0.4);
insert into agents (aname, city, percent) values ('Terry Jordan', 'Cibaregbeg Dua', 0.03);
insert into agents (aname, city, percent) values ('Tina Edwards', 'Nizhnyaya Tura', 0.2);
insert into agents (aname, city, percent) values ('Earl Olson', 'Alca', 0.55);
insert into agents (aname, city, percent) values ('Earl Elliott', 'Narathiwat', 0.2);
insert into agents (aname, city, percent) values ('Kevin Myers', 'Laweueng', 0.69);
insert into agents (aname, city, percent) values ('Randy Boyd', 'Karpacz', 0.26);
insert into agents (aname, city, percent) values ('Marie Armstrong', 'Shenavan', 0.22);
insert into agents (aname, city, percent) values ('Peter Griffin', 'Chat Trakan', 0.28);
insert into agents (aname, city, percent) values ('Patricia Garcia', 'Baraguá', 1.0);
insert into agents (aname, city, percent) values ('Janet Ortiz', 'Fontinha', 0.15);
insert into agents (aname, city, percent) values ('Virginia Holmes', 'Bandar-e ‘Asalūyeh', 0.51);
insert into agents (aname, city, percent) values ('Mary Rose', 'Soraya', 0.47);
insert into agents (aname, city, percent) values ('Kathy Harper', 'Huanggang', 0.58);
insert into agents (aname, city, percent) values ('Virginia Ellis', 'Flen', 0.8);
insert into agents (aname, city, percent) values ('Roger James', 'Ordino', 0.08);
insert into agents (aname, city, percent) values ('Antonio Willis', 'Krzeszów', 0.57);
insert into agents (aname, city, percent) values ('Johnny Nichols', 'Ennery', 0.19);
insert into agents (aname, city, percent) values ('Bobby Russell', 'Ergates', 0.59);
insert into agents (aname, city, percent) values ('Lillian Simpson', 'Riangbaring', 0.64);
insert into agents (aname, city, percent) values ('Lori Russell', 'Bolo', 0.77);
insert into agents (aname, city, percent) values ('George Fowler', 'Pinagsibaan', 0.53);
insert into agents (aname, city, percent) values ('Mark Hart', 'Beitan', 0.73);
insert into agents (aname, city, percent) values ('Judy Burton', 'Gupakan', 0.67);
insert into agents (aname, city, percent) values ('Doris Ryan', 'Hongguang', 0.57);
insert into agents (aname, city, percent) values ('Harold Knight', 'Ponta Grossa', 0.02);
insert into agents (aname, city, percent) values ('Carol Wood', 'Otradnaya', 0.86);
insert into agents (aname, city, percent) values ('Marilyn Wood', 'Luboń', 0.13);
insert into agents (aname, city, percent) values ('Dennis Hall', 'Tierimu', 0.63);
insert into agents (aname, city, percent) values ('Marie Watson', 'Xinbu', 0.14);
insert into agents (aname, city, percent) values ('Fred Daniels', 'Yuanqian', 0.76);
insert into agents (aname, city, percent) values ('Katherine Mills', 'Pontal', 0.72);
insert into agents (aname, city, percent) values ('Kevin Edwards', 'Huanchillas', 0.26);
insert into agents (aname, city, percent) values ('Anthony Olson', 'Baitang', 0.19);
insert into agents (aname, city, percent) values ('Cheryl Reid', 'Prokop’yevsk', 0.95);
insert into agents (aname, city, percent) values ('William Dean', 'Guanshan', 0.19);
insert into agents (aname, city, percent) values ('Joe Larson', 'Kesambilerenkrajan', 0.54);
insert into agents (aname, city, percent) values ('Alan Myers', 'San Pablo', 0.94);
insert into agents (aname, city, percent) values ('Betty Long', 'Daying', 0.83);
insert into agents (aname, city, percent) values ('Barbara Dixon', 'Laascaanood', 0.82);
insert into agents (aname, city, percent) values ('Harry Bishop', 'New Yekepa', 0.74);
insert into agents (aname, city, percent) values ('Tina Foster', 'Subottsi', 0.18);
insert into agents (aname, city, percent) values ('Mildred Moreno', 'Ngenden', 0.32);
insert into agents (aname, city, percent) values ('Deborah Franklin', 'Sundbyberg', 0.65);
insert into agents (aname, city, percent) values ('Charles Ruiz', 'Lubukalung', 0.92);
insert into agents (aname, city, percent) values ('Cheryl Day', 'Dziergowice', 0.27);
insert into agents (aname, city, percent) values ('Keith Rogers', 'Jinggan', 0.62);
insert into agents (aname, city, percent) values ('Randy Schmidt', 'Rasony', 0.06);
insert into agents (aname, city, percent) values ('Stephanie Mccoy', 'Solna', 0.23);
insert into agents (aname, city, percent) values ('Steven Romero', 'Magitang', 0.06);
insert into agents (aname, city, percent) values ('Lisa Porter', 'Jiamachi', 0.09);
insert into agents (aname, city, percent) values ('Andrew Johnston', 'Tegaldowo', 0.89);
insert into agents (aname, city, percent) values ('Raymond Rogers', 'Iksan', 0.67);
insert into agents (aname, city, percent) values ('Paul Myers', 'Nāṟay', 0.98);
insert into agents (aname, city, percent) values ('Christine Bell', 'Dniprodzerzhyns’k', 0.86);
insert into agents (aname, city, percent) values ('Sean Rogers', 'Suining', 0.86);
insert into agents (aname, city, percent) values ('Jean Dunn', 'Täby', 0.94);
insert into agents (aname, city, percent) values ('Ashley Russell', 'Sumiainen', 0.55);
insert into agents (aname, city, percent) values ('Eugene Spencer', 'Herrljunga', 0.84);
insert into agents (aname, city, percent) values ('Ann Crawford', 'Shal’skiy', 0.04);
insert into agents (aname, city, percent) values ('Ronald Fowler', 'Azteca', 0.99);
insert into agents (aname, city, percent) values ('Tammy Riley', 'Fëdorovskoye', 0.56);
insert into agents (aname, city, percent) values ('Diane Arnold', 'Świętajno', 0.49);
insert into agents (aname, city, percent) values ('Sandra Nelson', 'Zhuangbian', 0.44);
insert into agents (aname, city, percent) values ('Thomas Stevens', 'Weizhou', 0.09);
insert into agents (aname, city, percent) values ('Christine Lopez', 'Palanas', 0.75);
insert into agents (aname, city, percent) values ('Joshua Taylor', 'Pingshanhu', 0.1);
insert into agents (aname, city, percent) values ('Paul Gonzalez', 'Pacaraos', 0.35);
insert into agents (aname, city, percent) values ('Stephanie Dixon', 'Flor da Rosa', 0.11);
insert into agents (aname, city, percent) values ('Maria Alvarez', 'Biny Selo', 0.43);
insert into agents (aname, city, percent) values ('Lori Frazier', 'Matingain', 0.16);
insert into agents (aname, city, percent) values ('Ruth Brown', 'Pashkovskiy', 0.93);
insert into agents (aname, city, percent) values ('Judy Warren', 'Zhaocun', 0.61);
insert into agents (aname, city, percent) values ('Charles Ford', 'Krzczonów', 0.21);
insert into agents (aname, city, percent) values ('Jessica Ferguson', 'Lingkou', 0.97);
insert into agents (aname, city, percent) values ('Janet Bell', 'Bella Vista', 0.02);
insert into agents (aname, city, percent) values ('Dorothy Stone', 'Cacoal', 0.75);
insert into agents (aname, city, percent) values ('Rachel Watkins', 'Gadon', 0.2);
insert into agents (aname, city, percent) values ('Harry Mcdonald', 'Sikeshu', 0.66);
insert into agents (aname, city, percent) values ('Janet Lynch', 'Lauro de Freitas', 0.21);
insert into agents (aname, city, percent) values ('Brandon Grant', 'Saint-Étienne', 0.2);
insert into agents (aname, city, percent) values ('Deborah Evans', 'Galis Dua', 0.73);
insert into agents (aname, city, percent) values ('Randy Howell', 'Tanahbeureum', 0.09);
insert into agents (aname, city, percent) values ('Irene Oliver', 'Tutul', 0.37);
insert into agents (aname, city, percent) values ('Arthur Vasquez', 'Senhor do Bonfim', 0.72);
insert into agents (aname, city, percent) values ('Harold Martin', 'West End', 0.34);
insert into agents (aname, city, percent) values ('Debra Howard', 'Patea', 0.86);
insert into agents (aname, city, percent) values ('Jenny Doe', 'Stow', 0.33);
