insert into customers (cname, city, discnt) values ('Rebecca Olson', 'Sawoi', 0.16);
insert into customers (cname, city, discnt) values ('Rose Bowman', 'Abuja', 0.48);
insert into customers (cname, city, discnt) values ('Lawrence Rogers', 'Chocianów', 0.42);
insert into customers (cname, city, discnt) values ('Bruce Campbell', 'Stockholm', 0.69);
insert into customers (cname, city, discnt) values ('Karen Palmer', 'La Loma', 0.01);
insert into customers (cname, city, discnt) values ('Lawrence Gilbert', 'Mełgiew', 0.46);
insert into customers (cname, city, discnt) values ('Julie Rice', 'Pa Mok', null);
insert into customers (cname, city, discnt) values ('Maria Carpenter', 'Changfeng', null);
insert into customers (cname, city, discnt) values ('Paula Reed', 'Radès', 0.62);
insert into customers (cname, city, discnt) values ('Douglas Cook', 'Kapenguria', 0.96);
insert into customers (cname, city, discnt) values ('Diane Dunn', 'Icó', 0.26);
insert into customers (cname, city, discnt) values ('Anthony Lane', 'Rat Burana', 0.45);
insert into customers (cname, city, discnt) values ('Theresa Morrison', 'Balogo', 0.4);
insert into customers (cname, city, discnt) values ('Dorothy Walker', 'Qinghaihu', 0.73);
insert into customers (cname, city, discnt) values ('Kathy Collins', 'Dornava', 0.47);
insert into customers (cname, city, discnt) values ('Donald Rice', 'Kista', 0.22);
insert into customers (cname, city, discnt) values ('Kenneth Gonzales', 'Ilhéus', 0.04);
insert into customers (cname, city, discnt) values ('Joe Holmes', 'Tatabánya', null);
insert into customers (cname, city, discnt) values ('Tina Hicks', 'Jambuwerkrajan', 0.09);
insert into customers (cname, city, discnt) values ('Barbara Nichols', 'Qiandeng', null);
insert into customers (cname, city, discnt) values ('Jesse Knight', 'Kirkton', 0.7);
insert into customers (cname, city, discnt) values ('Stephen Peters', 'Santo Domingo', null);
insert into customers (cname, city, discnt) values ('Pamela West', 'Panenggoede', 0.48);
insert into customers (cname, city, discnt) values ('Heather Day', 'Blansko', 0.63);
insert into customers (cname, city, discnt) values ('Nancy Stephens', 'Mānānwāla', null);
insert into customers (cname, city, discnt) values ('Billy Kim', 'Plottier', 0.15);
insert into customers (cname, city, discnt) values ('Diane Mendoza', '‘Alīābād-e Katūl', 0.04);
insert into customers (cname, city, discnt) values ('Rachel Schmidt', 'Igrim', null);
insert into customers (cname, city, discnt) values ('Henry Webb', 'Diaowei', 0.82);
insert into customers (cname, city, discnt) values ('Samuel Shaw', 'Quimper', 0.83);
insert into customers (cname, city, discnt) values ('Kimberly Matthews', 'Dongchen', null);
insert into customers (cname, city, discnt) values ('Roy Reed', 'Perho', 0.01);
insert into customers (cname, city, discnt) values ('Debra James', 'Bayang', null);
insert into customers (cname, city, discnt) values ('Joan Howard', 'Lucheng', 0.26);
insert into customers (cname, city, discnt) values ('Carolyn Warren', 'Seltjarnarnes', 0.87);
insert into customers (cname, city, discnt) values ('Michelle Shaw', 'Wierzchucino', null);
insert into customers (cname, city, discnt) values ('Sean Lewis', 'Bella Vista', null);
insert into customers (cname, city, discnt) values ('Robin Larson', 'Choca do Mar', 0.64);
insert into customers (cname, city, discnt) values ('Timothy Sullivan', 'Rongxing', 0.36);
insert into customers (cname, city, discnt) values ('Norma Henderson', 'Khān Arnabah', null);
insert into customers (cname, city, discnt) values ('Michelle Cruz', 'Langkap', 0.22);
insert into customers (cname, city, discnt) values ('Jonathan Shaw', 'Las Palomas', 0.65);
insert into customers (cname, city, discnt) values ('Anthony Arnold', 'Hostomice', 0.64);
insert into customers (cname, city, discnt) values ('Norma Ward', 'Arcos', 0.42);
insert into customers (cname, city, discnt) values ('Clarence Wells', 'Las Breñas', 0.89);
insert into customers (cname, city, discnt) values ('Aaron Peters', 'Thakhèk', null);
insert into customers (cname, city, discnt) values ('Bobby Welch', 'Las Tablas', 0.86);
insert into customers (cname, city, discnt) values ('Shirley Hunt', 'Corupá', 0.44);
insert into customers (cname, city, discnt) values ('Marilyn Cruz', 'Takeo', 0.64);
insert into customers (cname, city, discnt) values ('Peter Allen', 'Madette', null);
insert into customers (cname, city, discnt) values ('Billy Roberts', 'Crespo', 0.2);
insert into customers (cname, city, discnt) values ('Lori Oliver', 'Haapajärvi', 0.47);
insert into customers (cname, city, discnt) values ('Howard Armstrong', 'Cibitung', null);
insert into customers (cname, city, discnt) values ('Jeremy Alvarez', 'Gocoton', null);
insert into customers (cname, city, discnt) values ('Billy Richards', 'Danderyd', null);
insert into customers (cname, city, discnt) values ('Shirley West', 'Hulyaypole', 0.22);
insert into customers (cname, city, discnt) values ('Juan Jones', 'Huerta Grande', null);
insert into customers (cname, city, discnt) values ('Shawn Black', 'Zhenyuan', 0.63);
insert into customers (cname, city, discnt) values ('Sean Taylor', 'Dingzhai', null);
insert into customers (cname, city, discnt) values ('Peter Dixon', 'Cimuncang', null);
insert into customers (cname, city, discnt) values ('Willie Price', 'Mūdīyah', 0.12);
insert into customers (cname, city, discnt) values ('Katherine Stone', 'Musalerr', 0.85);
insert into customers (cname, city, discnt) values ('Betty Daniels', 'Mirsíni', 0.44);
insert into customers (cname, city, discnt) values ('Anna Jones', 'Cikadu', null);
insert into customers (cname, city, discnt) values ('Margaret Ruiz', 'Pyrgetós', 0.16);
insert into customers (cname, city, discnt) values ('Earl Price', 'Gangmei', null);
insert into customers (cname, city, discnt) values ('Kelly Morris', 'Ullulluco', null);
insert into customers (cname, city, discnt) values ('Rachel Ruiz', 'Gharavŭtí', null);
insert into customers (cname, city, discnt) values ('Linda Gordon', 'Fengmu', null);
insert into customers (cname, city, discnt) values ('Janet Stone', 'Wang Saphung', null);
insert into customers (cname, city, discnt) values ('Jason Tucker', 'Zheleznodorozhnyy', 0.75);
insert into customers (cname, city, discnt) values ('Keith Brown', 'Yong’an', null);
insert into customers (cname, city, discnt) values ('Alice Palmer', 'Chaoshui', null);
insert into customers (cname, city, discnt) values ('Kathy Richards', 'Wasilków', null);
insert into customers (cname, city, discnt) values ('Kathryn Warren', 'Ma''an', 0.88);
insert into customers (cname, city, discnt) values ('Annie Hunt', 'Pantaihambawang', null);
insert into customers (cname, city, discnt) values ('Theresa Ryan', 'Mosty', null);
insert into customers (cname, city, discnt) values ('Pamela Olson', 'Novoukrainskiy', 0.34);
insert into customers (cname, city, discnt) values ('Andrea Parker', 'Krajan Puru', 0.59);
insert into customers (cname, city, discnt) values ('Samuel Welch', 'Kudus', 0.24);
insert into customers (cname, city, discnt) values ('Patricia Gonzales', 'Songnan', 0.83);
insert into customers (cname, city, discnt) values ('Katherine Anderson', 'Nantes', null);
insert into customers (cname, city, discnt) values ('Ralph George', 'Shuhong', null);
insert into customers (cname, city, discnt) values ('Emily Bennett', 'Calsib', 0.69);
insert into customers (cname, city, discnt) values ('Antonio Watkins', 'Kafachan', 0.81);
insert into customers (cname, city, discnt) values ('Bobby Dixon', 'Madimba', 0.1);
insert into customers (cname, city, discnt) values ('Stephen Harris', 'Hongshanyao', 0.52);
insert into customers (cname, city, discnt) values ('Kelly Simmons', 'Perstorp', 0.79);
insert into customers (cname, city, discnt) values ('Julia Ellis', 'Miguel Hidalgo', 0.14);
insert into customers (cname, city, discnt) values ('Martha Willis', 'Ranchuelo', 0.74);
insert into customers (cname, city, discnt) values ('John Day', 'Imtarfa', null);
insert into customers (cname, city, discnt) values ('Walter Gomez', 'Santa Ana', null);
insert into customers (cname, city, discnt) values ('Kenneth Harper', 'Tougan', 0.3);
insert into customers (cname, city, discnt) values ('Donna Alvarez', 'Nikolayevsk', 0.28);
insert into customers (cname, city, discnt) values ('Marie Nelson', 'Asahikawa', null);
insert into customers (cname, city, discnt) values ('Rose Powell', 'Sitrah', 0.68);
insert into customers (cname, city, discnt) values ('Harold Fowler', 'Zahedan', null);
insert into customers (cname, city, discnt) values ('Amy Taylor', 'Versailles', 0.92);
insert into customers (cname, city, discnt) values ('Donna Murray', 'Aracaju', 0.92);
insert into customers (cname, city, discnt) values ('Andrea Bishop', 'Viangxai', null);
insert into customers (cname, city, discnt) values ('Ruth Simpson', 'Leone', 0.04);
insert into customers (cname, city, discnt) values ('Frances Clark', 'Šabac', 0.32);
insert into customers (cname, city, discnt) values ('Wanda Porter', 'Patpata Segundo', null);
insert into customers (cname, city, discnt) values ('Louis Ray', 'Nozdrzec', null);
insert into customers (cname, city, discnt) values ('Joseph Little', 'Detchino', 0.89);
insert into customers (cname, city, discnt) values ('Kathryn Garza', 'Panguna', 0.55);
insert into customers (cname, city, discnt) values ('Sharon Knight', 'Mustvee', null);
insert into customers (cname, city, discnt) values ('Stephen Gonzales', 'Braço do Norte', 0.52);
insert into customers (cname, city, discnt) values ('Theresa White', 'P’asanauri', 0.26);
insert into customers (cname, city, discnt) values ('Sharon Simpson', 'Aso', 0.93);
insert into customers (cname, city, discnt) values ('Bonnie Rogers', 'La Goulette', null);
insert into customers (cname, city, discnt) values ('Diane Little', 'Awar-awar', null);
insert into customers (cname, city, discnt) values ('Antonio Garza', 'Zašová', null);
insert into customers (cname, city, discnt) values ('Annie Hart', 'Mosteiro', null);
insert into customers (cname, city, discnt) values ('Antonio Sanders', 'Paty do Alferes', 0.22);
insert into customers (cname, city, discnt) values ('Rachel Bailey', 'Ereira', 0.62);
insert into customers (cname, city, discnt) values ('Patricia Elliott', 'Wenxi', null);
insert into customers (cname, city, discnt) values ('Wayne Bowman', 'Farkhor', 0.87);
insert into customers (cname, city, discnt) values ('Richard Nichols', 'Tongxing', null);
insert into customers (cname, city, discnt) values ('Samuel Campbell', 'Pakham', null);
insert into customers (cname, city, discnt) values ('Lillian Dixon', 'Qīr', null);
insert into customers (cname, city, discnt) values ('Elizabeth Rice', 'La Broquerie', 0.82);
insert into customers (cname, city, discnt) values ('Gregory Bell', 'Buenavista', 0.05);
insert into customers (cname, city, discnt) values ('Joyce Edwards', 'Shuikou', 0.32);
insert into customers (cname, city, discnt) values ('Gloria Johnston', 'Shuqiao', null);
insert into customers (cname, city, discnt) values ('Jonathan Cox', 'Seixezelo', 0.31);
insert into customers (cname, city, discnt) values ('Pamela Marshall', 'Ayapel', null);
insert into customers (cname, city, discnt) values ('Antonio Carter', 'Timiryazevo', null);
insert into customers (cname, city, discnt) values ('Samuel Carr', 'Bobon', null);
insert into customers (cname, city, discnt) values ('Matthew Turner', 'Szamotuły', 0.34);
insert into customers (cname, city, discnt) values ('Frank Reid', 'Nenotes', null);
insert into customers (cname, city, discnt) values ('Martin Hicks', 'Xinxi', null);
insert into customers (cname, city, discnt) values ('Carl Jenkins', 'Dan Sadau', 0.65);
insert into customers (cname, city, discnt) values ('Ruth Matthews', 'MacArthur', 0.12);
insert into customers (cname, city, discnt) values ('Catherine Martin', 'Gouping', null);
insert into customers (cname, city, discnt) values ('Howard Edwards', 'Karang Daye', 0.06);
insert into customers (cname, city, discnt) values ('Nicole Morales', 'Sidikalang', 0.51);
insert into customers (cname, city, discnt) values ('Christina Franklin', 'Haibara', null);
insert into customers (cname, city, discnt) values ('Annie Wilson', 'Zastávka', null);
insert into customers (cname, city, discnt) values ('Arthur Harvey', 'Mocoa', 0.92);
insert into customers (cname, city, discnt) values ('Brenda Harper', 'Porto Feliz', 0.91);
insert into customers (cname, city, discnt) values ('Shawn Berry', 'Quartier Morin', null);
insert into customers (cname, city, discnt) values ('Ann Peters', 'Rublëvo', 0.41);
insert into customers (cname, city, discnt) values ('Stephen Larson', 'Port-Vila', 0.53);
insert into customers (cname, city, discnt) values ('Evelyn Garza', 'Merklín', 0.18);
insert into customers (cname, city, discnt) values ('Brenda Dean', 'Piggs Peak', null);
insert into customers (cname, city, discnt) values ('William Brown', 'Cikaduen', 0.18);
insert into customers (cname, city, discnt) values ('Kelly Olson', 'Meishan', null);
insert into customers (cname, city, discnt) values ('Beverly Gutierrez', 'Bojszowy Nowe', null);
insert into customers (cname, city, discnt) values ('Mary Bennett', 'Aqsū', 0.16);
insert into customers (cname, city, discnt) values ('John Young', 'Brotas', null);
insert into customers (cname, city, discnt) values ('Rose Perkins', 'Roslavl’', null);
insert into customers (cname, city, discnt) values ('Carl Banks', 'Neftegorsk', null);
insert into customers (cname, city, discnt) values ('Julia Bennett', 'Alvalade', 0.26);
insert into customers (cname, city, discnt) values ('Jean Baker', 'Boshan', 0.15);
insert into customers (cname, city, discnt) values ('Dennis Bennett', 'Kalkara', 0.28);
insert into customers (cname, city, discnt) values ('Jennifer Burns', 'Saint-Lambert-de-Lauzon', null);
insert into customers (cname, city, discnt) values ('Lori Edwards', 'Tuanshansi', null);
insert into customers (cname, city, discnt) values ('Craig Hawkins', 'Jianzhatan', 0.23);
insert into customers (cname, city, discnt) values ('Kelly Mills', 'Huquan', null);
insert into customers (cname, city, discnt) values ('Annie Franklin', 'Limbangan', null);
insert into customers (cname, city, discnt) values ('Russell Harrison', 'Ciechanowiec', 0.99);
insert into customers (cname, city, discnt) values ('Judith Palmer', 'Ríohacha', 0.87);
insert into customers (cname, city, discnt) values ('Raymond Ford', 'Menanga', 1.0);
insert into customers (cname, city, discnt) values ('Annie Cook', 'Beizhuang', 0.3);
insert into customers (cname, city, discnt) values ('Heather Alvarez', 'Udënisht', null);
insert into customers (cname, city, discnt) values ('Matthew Owens', 'Chengxi', null);
insert into customers (cname, city, discnt) values ('Brandon Castillo', 'Kemlya', null);
insert into customers (cname, city, discnt) values ('Nicole Robinson', 'Dalupirip', 0.43);
insert into customers (cname, city, discnt) values ('Earl Hansen', 'Sainte-Martine', 0.99);
insert into customers (cname, city, discnt) values ('Sharon Flores', 'Rancakole', 0.63);
insert into customers (cname, city, discnt) values ('Sarah Jordan', 'Santo Amaro', 0.36);
insert into customers (cname, city, discnt) values ('Larry Austin', 'Boise', 0.36);
insert into customers (cname, city, discnt) values ('Elizabeth Simmons', 'Dresden', 0.18);
insert into customers (cname, city, discnt) values ('Bobby Murphy', 'Saguing', 0.22);
insert into customers (cname, city, discnt) values ('Frances Willis', 'Xiuyu', 0.27);
insert into customers (cname, city, discnt) values ('James Mccoy', 'El Triunfo', null);
insert into customers (cname, city, discnt) values ('Jean Peterson', 'Zhanghekou', null);
insert into customers (cname, city, discnt) values ('Julia Lee', 'Libiąż', 0.33);
insert into customers (cname, city, discnt) values ('Steven Ryan', 'Paris 20', 0.93);
insert into customers (cname, city, discnt) values ('Debra Mcdonald', 'Lankaran', 0.34);
insert into customers (cname, city, discnt) values ('Jonathan Graham', 'Pangtangis Dajah', null);
insert into customers (cname, city, discnt) values ('Maria Hicks', 'Couto', 0.66);
insert into customers (cname, city, discnt) values ('Justin Arnold', 'Changtian', null);
insert into customers (cname, city, discnt) values ('Elizabeth Harvey', 'High Prairie', 0.61);
insert into customers (cname, city, discnt) values ('Jimmy Morrison', 'Lajas', null);
insert into customers (cname, city, discnt) values ('Harry Lawrence', 'Kertahayu', 0.24);
insert into customers (cname, city, discnt) values ('Amanda Washington', 'Le Havre', 0.43);
insert into customers (cname, city, discnt) values ('Carlos Ramirez', 'Beijie', 0.84);
insert into customers (cname, city, discnt) values ('Judith Hudson', 'Jinta', 0.84);
insert into customers (cname, city, discnt) values ('Jean Little', 'Kýthnos', null);
insert into customers (cname, city, discnt) values ('Elizabeth Kennedy', 'Mbale', 0.99);
insert into customers (cname, city, discnt) values ('Albert Wallace', 'Itaqui', null);
insert into customers (cname, city, discnt) values ('Julia Robertson', 'Brunflo', null);
insert into customers (cname, city, discnt) values ('Martha Hamilton', 'Jishi', null);
insert into customers (cname, city, discnt) values ('Walter Kim', 'Roissy Charles-de-Gaulle', null);
insert into customers (cname, city, discnt) values ('Martha Reyes', 'Lusambo', 0.43);
insert into customers (cname, city, discnt) values ('Joan Reed', 'Miechów Charsznica', 0.5);
insert into customers (cname, city, discnt) values ('Jimmy Montgomery', 'Magadan', 0.04);
insert into customers (cname, city, discnt) values ('Gloria Mitchell', 'Mānānwāla', 0.9);
insert into customers (cname, city, discnt) values ('Justin Robertson', 'Paços', null);
insert into customers (cname, city, discnt) values ('Jennifer Armstrong', 'Tari', null);
insert into customers (cname, city, discnt) values ('Charles Gibson', 'Marcq-en-Barœul', 0.11);
insert into customers (cname, city, discnt) values ('Todd Porter', 'Casais Baleal', 0.62);
insert into customers (cname, city, discnt) values ('Keith Martin', 'Menggusi', 0.56);
insert into customers (cname, city, discnt) values ('Lori Matthews', 'Balabagan', 0.6);
insert into customers (cname, city, discnt) values ('Mildred Lopez', 'Monte Branco', null);
insert into customers (cname, city, discnt) values ('Nancy Pierce', 'Berlin', 0.7);
insert into customers (cname, city, discnt) values ('Michael Hart', 'Cibinong', 0.49);
insert into customers (cname, city, discnt) values ('Theresa Nelson', 'Tibiri', null);
insert into customers (cname, city, discnt) values ('Alice Rice', 'Elói Mendes', 0.08);
insert into customers (cname, city, discnt) values ('Katherine Campbell', 'Zhendong', null);
insert into customers (cname, city, discnt) values ('Kathy Stevens', 'Caen', 0.74);
insert into customers (cname, city, discnt) values ('Wayne Cruz', 'Machida', null);
insert into customers (cname, city, discnt) values ('Robert Jacobs', 'Shin’ichi', 0.53);
insert into customers (cname, city, discnt) values ('Heather Robertson', 'Janja', 0.48);
insert into customers (cname, city, discnt) values ('Earl Hicks', 'San Pedro Ayampuc', 0.56);
insert into customers (cname, city, discnt) values ('Deborah Allen', 'Beiling', null);
insert into customers (cname, city, discnt) values ('Steve Howard', 'San Jerónimo', 0.67);
insert into customers (cname, city, discnt) values ('Todd Williams', 'Dobšice', 0.83);
insert into customers (cname, city, discnt) values ('Wayne Peters', 'Haoguantun', 0.81);
insert into customers (cname, city, discnt) values ('Rachel Rodriguez', 'Ninomiya', 0.5);
insert into customers (cname, city, discnt) values ('Jeffrey West', 'Starokucherganovka', 0.94);
insert into customers (cname, city, discnt) values ('Jeremy Sims', 'Sukagawa', 0.99);
insert into customers (cname, city, discnt) values ('Janice Rivera', 'Sneek', null);
insert into customers (cname, city, discnt) values ('Mary Sanchez', 'Sedati', 0.43);
insert into customers (cname, city, discnt) values ('Evelyn Ford', 'Pasirpengarayan', null);
insert into customers (cname, city, discnt) values ('Wanda Reed', 'Pakemitan', 0.44);
insert into customers (cname, city, discnt) values ('Margaret Payne', 'Amparafaravola', null);
insert into customers (cname, city, discnt) values ('Ruby Snyder', 'Norsborg', null);
insert into customers (cname, city, discnt) values ('Gregory Vasquez', 'Quince Mil', null);
insert into customers (cname, city, discnt) values ('Frank Spencer', 'Lodan Wetan', null);
insert into customers (cname, city, discnt) values ('Matthew Baker', 'Viesīte', 0.37);
insert into customers (cname, city, discnt) values ('Antonio Elliott', 'Jaruco', 0.18);
insert into customers (cname, city, discnt) values ('Helen Cole', 'Changling', 0.26);
insert into customers (cname, city, discnt) values ('Ernest Rice', 'Al Qurayn', null);
insert into customers (cname, city, discnt) values ('Brian Berry', 'Kamiiso', 0.99);
insert into customers (cname, city, discnt) values ('Alice Rogers', 'Stratónion', 0.0);
insert into customers (cname, city, discnt) values ('Andrew Campbell', 'Wadusari', 0.0);
insert into customers (cname, city, discnt) values ('Nicholas Olson', 'Savonranta', null);
insert into customers (cname, city, discnt) values ('Earl Hawkins', 'Sölvesborg', null);
insert into customers (cname, city, discnt) values ('Carlos Riley', 'Guadalupe', 0.85);
insert into customers (cname, city, discnt) values ('Brian Stephens', 'Akankpa', 0.25);
insert into customers (cname, city, discnt) values ('Dorothy Watkins', 'Baiyang', 0.59);
insert into customers (cname, city, discnt) values ('Helen Bailey', 'Qinlan', 0.02);
insert into customers (cname, city, discnt) values ('Jeremy Alvarez', 'Bangolo', 0.21);
insert into customers (cname, city, discnt) values ('Earl Mcdonald', 'Suphan Buri', 0.21);
insert into customers (cname, city, discnt) values ('Joe West', 'Paris La Défense', null);
insert into customers (cname, city, discnt) values ('Timothy Williams', '‘Ibrī', 0.97);
insert into customers (cname, city, discnt) values ('Ernest Olson', 'Tsákoi', null);
insert into customers (cname, city, discnt) values ('Ashley Hicks', 'Marinhais', 0.06);
insert into customers (cname, city, discnt) values ('Larry Evans', 'Barisāl', null);
insert into customers (cname, city, discnt) values ('Betty Rogers', 'Iza', 0.68);
insert into customers (cname, city, discnt) values ('Clarence Lee', 'Tanqiao', 0.91);
insert into customers (cname, city, discnt) values ('Elizabeth Turner', 'Jiasi', null);
insert into customers (cname, city, discnt) values ('Richard Freeman', 'Pianling', 0.61);
insert into customers (cname, city, discnt) values ('Carolyn Perkins', 'Longzhou', 0.66);
insert into customers (cname, city, discnt) values ('Ernest Daniels', 'Duishan', null);
insert into customers (cname, city, discnt) values ('Melissa Walker', 'Shaliu', null);
insert into customers (cname, city, discnt) values ('Elizabeth Dixon', 'La Floresta', null);
insert into customers (cname, city, discnt) values ('Douglas Fox', 'Marcovia', 0.51);
insert into customers (cname, city, discnt) values ('Annie Edwards', 'Yanhong', 0.33);
insert into customers (cname, city, discnt) values ('Lois Dunn', 'Ciangir', 0.69);
insert into customers (cname, city, discnt) values ('Donald Johnson', 'Celestynów', null);
insert into customers (cname, city, discnt) values ('Lisa Warren', 'Ježdovec', 0.1);
insert into customers (cname, city, discnt) values ('Ralph Henderson', 'Xiawa', null);
insert into customers (cname, city, discnt) values ('Stephen Bailey', 'Tanggu', 0.92);
insert into customers (cname, city, discnt) values ('Louise Duncan', 'Krajan Dua Patempuran', 0.19);
insert into customers (cname, city, discnt) values ('Nicole Ferguson', 'Moutas', null);
insert into customers (cname, city, discnt) values ('Annie Williams', 'Tuatuka', null);
insert into customers (cname, city, discnt) values ('Donna Fowler', 'Bełk', null);
insert into customers (cname, city, discnt) values ('Sharon Kelly', 'Waldbillig', 0.18);
insert into customers (cname, city, discnt) values ('Timothy Griffin', 'Marcabamba', null);
insert into customers (cname, city, discnt) values ('Janet Scott', 'Dikwa', 0.71);
insert into customers (cname, city, discnt) values ('Steve Ramos', 'Novi Slankamen', null);
insert into customers (cname, city, discnt) values ('Alan Foster', 'Spas-Zaulok', 0.4);
insert into customers (cname, city, discnt) values ('Terry Payne', 'Rawang', null);
insert into customers (cname, city, discnt) values ('Eric Pierce', 'Shanghu', null);
insert into customers (cname, city, discnt) values ('Phyllis Ortiz', 'Le Lamentin', null);
insert into customers (cname, city, discnt) values ('Robert Davis', 'Kawalimukti', 0.87);
insert into customers (cname, city, discnt) values ('Joshua Jacobs', 'Freixo de Numão', 0.75);
insert into customers (cname, city, discnt) values ('Anna Holmes', 'Kandy', 0.43);
insert into customers (cname, city, discnt) values ('Steve Powell', 'Leudelange', null);
insert into customers (cname, city, discnt) values ('Martha Smith', 'Esuk Oron', 1.0);
insert into customers (cname, city, discnt) values ('Lois Reynolds', 'Ḩabīl al Jabr', 0.34);
insert into customers (cname, city, discnt) values ('Catherine Dean', 'Khallat Ḩamāmah', null);
insert into customers (cname, city, discnt) values ('Bruce Kim', 'Feuknoni', null);
insert into customers (cname, city, discnt) values ('Paula Hayes', 'Bulung’ur', 0.37);
insert into customers (cname, city, discnt) values ('Susan Parker', 'Napuro', null);
insert into customers (cname, city, discnt) values ('Bonnie Alvarez', 'Shahrisabz Shahri', null);
insert into customers (cname, city, discnt) values ('Betty Garcia', 'Guinoaliuan', null);
insert into customers (cname, city, discnt) values ('Diane Gutierrez', 'Dmytrivka', null);
insert into customers (cname, city, discnt) values ('Heather Peters', 'Langchuan', null);
insert into customers (cname, city, discnt) values ('Ann Lynch', 'Souto do Meio', 0.07);
insert into customers (cname, city, discnt) values ('Mark Alvarez', 'Ashchysay', null);
insert into customers (cname, city, discnt) values ('Douglas Grant', 'Chipaque', null);
insert into customers (cname, city, discnt) values ('Theresa Collins', 'Huanggang', null);
insert into customers (cname, city, discnt) values ('Justin Grant', 'Montepuez', 0.69);
insert into customers (cname, city, discnt) values ('Judy Wallace', 'Rakhiv', 0.73);
insert into customers (cname, city, discnt) values ('Emily Davis', 'Longbu', null);
insert into customers (cname, city, discnt) values ('Earl Young', 'Ortega', 0.01);
insert into customers (cname, city, discnt) values ('James Graham', 'Shu', null);
insert into customers (cname, city, discnt) values ('Ruth Moore', 'Pristen’', null);
insert into customers (cname, city, discnt) values ('Linda Pierce', 'Beringin', 0.04);
insert into customers (cname, city, discnt) values ('Charles Stephens', 'Ḩajjah', null);
insert into customers (cname, city, discnt) values ('Sara Ortiz', 'Mégara', 0.31);
insert into customers (cname, city, discnt) values ('Harry Cooper', 'Bayuwan', 0.16);
insert into customers (cname, city, discnt) values ('Virginia Hughes', 'Mamasa', null);
insert into customers (cname, city, discnt) values ('Douglas Weaver', 'Thị Trấn Sìn Hồ', null);
insert into customers (cname, city, discnt) values ('Martin Rodriguez', 'Kiukasen', null);
insert into customers (cname, city, discnt) values ('Annie Flores', 'Zhanlong', null);
insert into customers (cname, city, discnt) values ('Christina Perez', 'Río Blanco', 0.78);
insert into customers (cname, city, discnt) values ('Julie Henry', 'Taipingying', null);
insert into customers (cname, city, discnt) values ('Charles Hayes', 'Songjiang', 0.12);
insert into customers (cname, city, discnt) values ('Walter Wood', 'Simpang', null);
insert into customers (cname, city, discnt) values ('Matthew Crawford', 'Klichaw', null);
insert into customers (cname, city, discnt) values ('Debra Rodriguez', 'La Bélgica', null);
insert into customers (cname, city, discnt) values ('Karen Rose', 'Trąbki Wielkie', null);
insert into customers (cname, city, discnt) values ('George Vasquez', 'San Antonio', null);
insert into customers (cname, city, discnt) values ('Justin Johnson', 'Puerto Berrío', null);
insert into customers (cname, city, discnt) values ('Eugene Griffin', 'Los Pinos', null);
insert into customers (cname, city, discnt) values ('Angela Lane', 'Köneürgench', 0.61);
insert into customers (cname, city, discnt) values ('Arthur Foster', 'Lampa', 0.26);
insert into customers (cname, city, discnt) values ('Ashley Gonzales', 'Situ', 0.98);
insert into customers (cname, city, discnt) values ('Anne Ellis', 'Kansas City', null);
insert into customers (cname, city, discnt) values ('Jennifer Gomez', 'Mungging', 0.05);
insert into customers (cname, city, discnt) values ('Jane Webb', 'Shima', null);
insert into customers (cname, city, discnt) values ('Juan Mitchell', 'Zombo', null);
insert into customers (cname, city, discnt) values ('Linda Henry', 'Kuala Lumpur', 0.1);
insert into customers (cname, city, discnt) values ('Charles Harris', 'Kouango', null);
insert into customers (cname, city, discnt) values ('Ronald Sims', 'Torino', null);
insert into customers (cname, city, discnt) values ('Jason Marshall', 'Ticllos', null);
insert into customers (cname, city, discnt) values ('Helen Bishop', 'Nowshera', null);
insert into customers (cname, city, discnt) values ('Randy Ramos', 'Wudangshan', null);
insert into customers (cname, city, discnt) values ('Carl Watson', 'Nguken', null);
insert into customers (cname, city, discnt) values ('Roger Andrews', 'Dalamdesa Kalapadua', null);
insert into customers (cname, city, discnt) values ('Ryan Barnes', 'Kampungladang', 0.25);
insert into customers (cname, city, discnt) values ('Matthew Welch', 'Nusajaya', 0.14);
insert into customers (cname, city, discnt) values ('Gloria Russell', 'Bello', null);
insert into customers (cname, city, discnt) values ('Joan Ryan', 'Warin Chamrap', null);
insert into customers (cname, city, discnt) values ('Irene Ford', 'Mantang', null);
insert into customers (cname, city, discnt) values ('Gloria Carr', 'Lasek', 0.42);
insert into customers (cname, city, discnt) values ('Joshua Brown', 'Dungkek Laok', 0.52);
insert into customers (cname, city, discnt) values ('Annie Lawson', 'Tangchi', 0.94);
insert into customers (cname, city, discnt) values ('Robert Edwards', 'Haquira', 0.7);
insert into customers (cname, city, discnt) values ('Johnny Hayes', 'Oltinko’l', null);
insert into customers (cname, city, discnt) values ('Stephen Moreno', 'Khao Wong', 0.76);
insert into customers (cname, city, discnt) values ('Eric Miller', 'Xieyang', null);
insert into customers (cname, city, discnt) values ('Gloria Carroll', 'Haodi', 0.7);
insert into customers (cname, city, discnt) values ('Christina Scott', 'Itanhaém', 0.54);
insert into customers (cname, city, discnt) values ('Billy Ward', 'Guxi', null);
insert into customers (cname, city, discnt) values ('Mark Morrison', 'Siikainen', null);
insert into customers (cname, city, discnt) values ('Earl Hansen', 'Sanchahe', 0.52);
insert into customers (cname, city, discnt) values ('Rose Reyes', 'Bolesławiec', null);
insert into customers (cname, city, discnt) values ('Randy Fernandez', 'Cangkeuteuk Sabrang', 0.21);
insert into customers (cname, city, discnt) values ('Gregory Freeman', 'Hekou', null);
insert into customers (cname, city, discnt) values ('Joshua Henry', 'Berlin', null);
insert into customers (cname, city, discnt) values ('Doris Hughes', 'San Vicente de Moravia', 0.86);
insert into customers (cname, city, discnt) values ('Annie Murray', 'Shanban', 0.94);
insert into customers (cname, city, discnt) values ('Mary Reed', 'Laspezia', null);
insert into customers (cname, city, discnt) values ('Patrick Scott', 'Göteborg', null);
insert into customers (cname, city, discnt) values ('Joe Nelson', 'Gaya', 0.8);
insert into customers (cname, city, discnt) values ('Marilyn Jenkins', 'Shatoujiao', 0.81);
insert into customers (cname, city, discnt) values ('Robert Hart', 'Ryazanskiy', 0.36);
insert into customers (cname, city, discnt) values ('Robert Hamilton', 'Varāmīn', null);
insert into customers (cname, city, discnt) values ('Irene Matthews', 'Kuandian', 0.18);
insert into customers (cname, city, discnt) values ('Douglas Hall', 'Cosmópolis', 0.13);
insert into customers (cname, city, discnt) values ('Christopher Hughes', 'Chon Daen', 0.48);
insert into customers (cname, city, discnt) values ('Patrick Kelly', 'Nōgata', 0.08);
insert into customers (cname, city, discnt) values ('Sean Allen', 'Suan Luang', 0.03);
insert into customers (cname, city, discnt) values ('Michelle Bradley', 'Kotauneng', null);
insert into customers (cname, city, discnt) values ('Frank Roberts', 'Aguas Verdes', 0.05);
insert into customers (cname, city, discnt) values ('Sharon Kelly', 'Panghadangan', null);
insert into customers (cname, city, discnt) values ('Stephanie Cooper', 'Neẖalim', null);
insert into customers (cname, city, discnt) values ('Ruth Bishop', 'Dera Murād Jamāli', null);
insert into customers (cname, city, discnt) values ('Fred Mendoza', 'Tempuran', null);
insert into customers (cname, city, discnt) values ('Janice Wright', 'Vrede', 0.37);
insert into customers (cname, city, discnt) values ('Rose Hunt', 'Kitui', 0.83);
insert into customers (cname, city, discnt) values ('Michael Bowman', 'Tianzhou', null);
insert into customers (cname, city, discnt) values ('Virginia Pierce', 'Issoudun', null);
insert into customers (cname, city, discnt) values ('George Grant', 'Tulungrejo', null);
insert into customers (cname, city, discnt) values ('Jessica Montgomery', 'Zhenlong', 0.88);
insert into customers (cname, city, discnt) values ('Brenda Lawrence', 'Genova', 0.57);
insert into customers (cname, city, discnt) values ('Eric Cox', 'Namibe', 0.9);
insert into customers (cname, city, discnt) values ('Walter Carroll', 'Cemplang', null);
insert into customers (cname, city, discnt) values ('Jane Bryant', 'Desa Margaluyu', null);
insert into customers (cname, city, discnt) values ('Paul Greene', 'Ina', null);
insert into customers (cname, city, discnt) values ('Andrew Hunt', 'Barnaul', null);
insert into customers (cname, city, discnt) values ('Randy Nelson', 'Mauhao', 0.02);
insert into customers (cname, city, discnt) values ('Helen Ramirez', 'San Francisco', null);
insert into customers (cname, city, discnt) values ('Juan Mcdonald', 'Amarillo', null);
insert into customers (cname, city, discnt) values ('Melissa Bailey', 'Thanh Chương', null);
insert into customers (cname, city, discnt) values ('Stephanie Bennett', 'Mendī', null);
insert into customers (cname, city, discnt) values ('Matthew Kelley', 'Manolo Fortich', 0.55);
insert into customers (cname, city, discnt) values ('Randy Bailey', 'Tegalgede Kulon', 0.15);
insert into customers (cname, city, discnt) values ('Bobby Alvarez', 'Tangkolo', null);
insert into customers (cname, city, discnt) values ('Sara Lawson', 'Musalerr', 0.95);
insert into customers (cname, city, discnt) values ('Nicholas Bennett', 'Boujniba', null);
insert into customers (cname, city, discnt) values ('Rebecca Harris', 'Janów', null);
insert into customers (cname, city, discnt) values ('Doris Green', 'Oenpeotnai', 0.67);
insert into customers (cname, city, discnt) values ('Irene Larson', 'São José do Rio Pardo', 0.74);
insert into customers (cname, city, discnt) values ('Janet Warren', 'Al Mazra‘ah', 0.86);
insert into customers (cname, city, discnt) values ('Beverly Patterson', 'Utama Wetan', 0.89);
insert into customers (cname, city, discnt) values ('Janice Olson', 'Santa Maria da Feira', null);
insert into customers (cname, city, discnt) values ('Stephanie Hamilton', 'Qīr Moāv', null);
insert into customers (cname, city, discnt) values ('Harold Jenkins', 'Kalianyar Selatan', null);
insert into customers (cname, city, discnt) values ('Albert Ward', 'Inari', 0.33);
insert into customers (cname, city, discnt) values ('Billy Larson', 'Ríohacha', null);
insert into customers (cname, city, discnt) values ('Sharon Ward', 'Lutoryż', 0.68);
insert into customers (cname, city, discnt) values ('Kenneth Wheeler', 'Hrvatska Kostajnica', 0.09);
insert into customers (cname, city, discnt) values ('Doris Tucker', 'Pahing Jalatrang', null);
insert into customers (cname, city, discnt) values ('Debra Berry', 'Lungmar', null);
insert into customers (cname, city, discnt) values ('Betty King', 'Puerto Rico', null);
insert into customers (cname, city, discnt) values ('Harold Porter', 'New York City', null);
insert into customers (cname, city, discnt) values ('Annie Ruiz', 'Qiligang', null);
insert into customers (cname, city, discnt) values ('Theresa Jenkins', 'Rennes', null);
insert into customers (cname, city, discnt) values ('Eric Dunn', 'Zhanxu', null);
insert into customers (cname, city, discnt) values ('Adam Knight', 'Qiulu', null);
insert into customers (cname, city, discnt) values ('Gary Garza', 'Shanhou', 0.13);
insert into customers (cname, city, discnt) values ('Gloria Marshall', 'Mucifal', null);
insert into customers (cname, city, discnt) values ('Joe Barnes', 'Damiku', 0.94);
insert into customers (cname, city, discnt) values ('Jeremy Sims', 'Comitancillo', 0.08);
insert into customers (cname, city, discnt) values ('Dennis Reynolds', 'Malangwa', 0.77);
insert into customers (cname, city, discnt) values ('Kimberly Harvey', 'Sanguanzhai', null);
insert into customers (cname, city, discnt) values ('Phillip Collins', 'Yong’an', 0.12);
insert into customers (cname, city, discnt) values ('Jason Turner', 'Poxin', 0.51);
insert into customers (cname, city, discnt) values ('Julie Wells', 'Vairão', 0.52);
insert into customers (cname, city, discnt) values ('Annie Baker', 'Changling', null);
insert into customers (cname, city, discnt) values ('Joseph Crawford', 'Phra Phutthabat', 0.44);
insert into customers (cname, city, discnt) values ('Eric Bishop', 'Cegłów', 0.42);
insert into customers (cname, city, discnt) values ('Ryan Butler', 'Barra de São Francisco', 0.53);
insert into customers (cname, city, discnt) values ('Lawrence Bailey', 'Neuilly-sur-Marne', 0.34);
insert into customers (cname, city, discnt) values ('Johnny Hayes', 'Wanfang', 0.37);
insert into customers (cname, city, discnt) values ('Benjamin Burke', 'Petrozavodsk', 0.82);
insert into customers (cname, city, discnt) values ('Anthony Howell', 'Mabini', null);
insert into customers (cname, city, discnt) values ('Ryan Jacobs', 'Paseyan', 0.7);
insert into customers (cname, city, discnt) values ('Phillip Medina', 'Bachaquero', null);
insert into customers (cname, city, discnt) values ('Martin Greene', 'Fafe', 0.23);
insert into customers (cname, city, discnt) values ('Denise Washington', 'Hulei', null);
insert into customers (cname, city, discnt) values ('Frances Owens', 'Cintra', null);
insert into customers (cname, city, discnt) values ('Bonnie Ray', 'Nanae', null);
insert into customers (cname, city, discnt) values ('Jesse Martin', 'Lucma', null);
insert into customers (cname, city, discnt) values ('Paula Carr', 'Seleuš', null);
insert into customers (cname, city, discnt) values ('Johnny Holmes', 'Sicaya', 1.0);
insert into customers (cname, city, discnt) values ('David Clark', 'Pospelikha', null);
insert into customers (cname, city, discnt) values ('Theresa Coleman', 'Zuobude', 0.56);
insert into customers (cname, city, discnt) values ('Keith Patterson', 'Pavlohrad', 0.22);
insert into customers (cname, city, discnt) values ('Juan Cruz', 'Dazi', null);
insert into customers (cname, city, discnt) values ('Rachel Stewart', 'Puconci', null);
insert into customers (cname, city, discnt) values ('Craig Gutierrez', 'Kotikawatta', null);
insert into customers (cname, city, discnt) values ('Joe Rivera', 'Dobropillya', null);
insert into customers (cname, city, discnt) values ('Linda Henderson', 'San Cosme y Damián', 0.48);
insert into customers (cname, city, discnt) values ('Carol Griffin', 'Aksu', null);
insert into customers (cname, city, discnt) values ('Albert Henderson', 'Cayna', null);
insert into customers (cname, city, discnt) values ('Scott Hart', 'San Martin', 0.46);
insert into customers (cname, city, discnt) values ('William Rogers', 'Standerton', null);
insert into customers (cname, city, discnt) values ('Antonio Richards', 'Chengjiao', null);
insert into customers (cname, city, discnt) values ('Michael Jordan', 'Rizómata', 0.64);
insert into customers (cname, city, discnt) values ('Tammy Martin', 'Labuhan Deli', null);
insert into customers (cname, city, discnt) values ('Ruby Carr', 'Anning', null);
insert into customers (cname, city, discnt) values ('Deborah Lopez', 'Chinameca', null);
insert into customers (cname, city, discnt) values ('Cynthia Sanders', 'Masvingo', 0.68);
insert into customers (cname, city, discnt) values ('Ernest Cole', 'Reriz', 0.9);
insert into customers (cname, city, discnt) values ('Jennifer Hughes', 'Rumāh', 0.8);
insert into customers (cname, city, discnt) values ('Antonio Watkins', 'Orekhovo-Zuyevo', 0.06);
insert into customers (cname, city, discnt) values ('Charles Fernandez', 'Laliki', 0.54);
insert into customers (cname, city, discnt) values ('Harold Cox', 'Ongabelen', 0.1);
insert into customers (cname, city, discnt) values ('Frances Weaver', 'Páno Polemídia', null);
insert into customers (cname, city, discnt) values ('Janice Johnson', 'Nakatsugawa', null);
insert into customers (cname, city, discnt) values ('Rose Bishop', 'Minggang', 0.91);
insert into customers (cname, city, discnt) values ('Harold Bell', 'Kunshan', null);
insert into customers (cname, city, discnt) values ('Eugene Cruz', 'Raczki', 0.66);
insert into customers (cname, city, discnt) values ('David Howell', 'Truskavets', null);
insert into customers (cname, city, discnt) values ('Fred Oliver', 'Inazawa', null);
insert into customers (cname, city, discnt) values ('Ronald Barnes', 'Were Īlu', null);
insert into customers (cname, city, discnt) values ('Wayne Bryant', 'Fahraj', null);
insert into customers (cname, city, discnt) values ('Judith Butler', 'Wilwerwiltz', 0.91);
insert into customers (cname, city, discnt) values ('Christine Franklin', 'Bunisari', null);
insert into customers (cname, city, discnt) values ('Julie Cooper', 'Lavradio', null);
insert into customers (cname, city, discnt) values ('Christina Boyd', 'Strumica', 0.21);
insert into customers (cname, city, discnt) values ('Todd Turner', 'Chittagong', null);
insert into customers (cname, city, discnt) values ('Dennis Wagner', 'Itaboraí', null);
insert into customers (cname, city, discnt) values ('Jimmy Willis', 'Arroyo Naranjo', null);
insert into customers (cname, city, discnt) values ('Lillian Kim', 'Maojiadian', null);
insert into customers (cname, city, discnt) values ('Harold Daniels', 'Chaupimarca', 0.79);
insert into customers (cname, city, discnt) values ('Steven Fields', 'Wailiang', null);
insert into customers (cname, city, discnt) values ('Patricia Cunningham', 'Týn nad Vltavou', null);
insert into customers (cname, city, discnt) values ('Philip Franklin', 'Ovidiopol’', null);
insert into customers (cname, city, discnt) values ('Roger Carr', 'Jiulian', null);
insert into customers (cname, city, discnt) values ('Carlos Diaz', 'San Rafael', null);
insert into customers (cname, city, discnt) values ('Arthur Armstrong', 'Szombathely', null);
insert into customers (cname, city, discnt) values ('Irene Hicks', 'Luotaping', 0.61);
insert into customers (cname, city, discnt) values ('Ralph Jones', 'Arauco', null);
insert into customers (cname, city, discnt) values ('Maria Evans', 'Karangpocok', 0.16);
insert into customers (cname, city, discnt) values ('Russell Snyder', 'San José de Bocay', 0.5);
insert into customers (cname, city, discnt) values ('Joseph Dixon', 'Stare Juchy', 0.42);
insert into customers (cname, city, discnt) values ('Dennis Chavez', 'Xindian', 0.18);
insert into customers (cname, city, discnt) values ('Louise Perry', 'Nackawic', null);
insert into customers (cname, city, discnt) values ('Frances Simmons', 'Tocok', null);
insert into customers (cname, city, discnt) values ('Edward Gonzales', 'Al ‘Anān', 0.44);
insert into customers (cname, city, discnt) values ('Steve Medina', 'Washington', null);
insert into customers (cname, city, discnt) values ('Shawn Williams', 'Reims', 0.86);
insert into customers (cname, city, discnt) values ('Adam Harris', 'Surin', 0.97);
insert into customers (cname, city, discnt) values ('Louis Ross', 'Joutseno', null);
insert into customers (cname, city, discnt) values ('Jane Brown', 'Sukamulya', 0.49);
insert into customers (cname, city, discnt) values ('Willie Simmons', 'Takefu', 0.43);
insert into customers (cname, city, discnt) values ('Martin Stewart', 'Thaba Nchu', 0.13);
insert into customers (cname, city, discnt) values ('Tina Morales', 'Liuduzhai', null);
insert into customers (cname, city, discnt) values ('Joshua Bell', 'Dhaka', null);
insert into customers (cname, city, discnt) values ('Brandon Andrews', 'Thị Trấn Vạn Hà', 0.37);
insert into customers (cname, city, discnt) values ('Julie Henderson', 'Kelaniya', null);
insert into customers (cname, city, discnt) values ('Annie Snyder', 'Troitsk', null);
insert into customers (cname, city, discnt) values ('Phyllis Howell', 'Zevgolateió', 0.92);
insert into customers (cname, city, discnt) values ('Lawrence Evans', 'Njivice', null);
insert into customers (cname, city, discnt) values ('Anthony Henry', 'Barobo', 0.31);
insert into customers (cname, city, discnt) values ('Virginia Johnston', 'Pomichna', 0.54);
insert into customers (cname, city, discnt) values ('Dorothy Armstrong', 'Kantharalak', 0.79);
insert into customers (cname, city, discnt) values ('Johnny Snyder', 'Kaligutan', 0.11);
insert into customers (cname, city, discnt) values ('Pamela Ellis', 'Jimo', null);
insert into customers (cname, city, discnt) values ('Kimberly Alexander', 'Šipovo', null);
insert into customers (cname, city, discnt) values ('Catherine Sims', 'Zolotkovo', 0.01);
insert into customers (cname, city, discnt) values ('Lawrence Murphy', 'Phoenix', 0.73);
insert into customers (cname, city, discnt) values ('George Snyder', 'Kalibuntu', 0.08);
insert into customers (cname, city, discnt) values ('Randy Collins', 'Miami', null);
insert into customers (cname, city, discnt) values ('Lisa Ferguson', 'Goúrnes', null);
insert into customers (cname, city, discnt) values ('Amanda Hudson', 'Weibin', null);
insert into customers (cname, city, discnt) values ('Nancy Chavez', 'Hafnarfjörður', null);
insert into customers (cname, city, discnt) values ('Shirley Watson', 'Giesteira', 0.27);
insert into customers (cname, city, discnt) values ('Carolyn James', 'Onueke', 0.66);
insert into customers (cname, city, discnt) values ('Bruce James', 'Bol’shoye Skuratovo', 0.53);
insert into customers (cname, city, discnt) values ('Brian Perez', 'Kashar', null);
insert into customers (cname, city, discnt) values ('Martin Edwards', 'Jetak', 0.37);
insert into customers (cname, city, discnt) values ('Mary Welch', 'Pryamitsyno', 0.59);
insert into customers (cname, city, discnt) values ('Gregory Fisher', 'Bianba', null);
insert into customers (cname, city, discnt) values ('Roy Thomas', 'Vasilikón', null);
insert into customers (cname, city, discnt) values ('Fred Evans', 'Oranjestad', null);
insert into customers (cname, city, discnt) values ('Theresa Hayes', 'Kota Kinabalu', null);
insert into customers (cname, city, discnt) values ('Norma Ford', 'Vredefort', 0.31);
insert into customers (cname, city, discnt) values ('Eugene West', 'Markala', 0.29);
insert into customers (cname, city, discnt) values ('Matthew Jenkins', 'Thị Trấn Ngan Dừa', null);
insert into customers (cname, city, discnt) values ('Craig Martin', 'Changtang', 0.19);
insert into customers (cname, city, discnt) values ('James Robinson', 'Skrzyszów', 0.75);
insert into customers (cname, city, discnt) values ('Dorothy Martin', 'Linmansangan', 0.29);
insert into customers (cname, city, discnt) values ('Evelyn Greene', 'Bunut', null);
insert into customers (cname, city, discnt) values ('Gerald Knight', 'Liuheng', 0.52);
insert into customers (cname, city, discnt) values ('Brenda Evans', 'Shimodate', null);
insert into customers (cname, city, discnt) values ('Teresa Olson', 'Ulricehamn', 0.26);
insert into customers (cname, city, discnt) values ('Nicole Hall', 'Ponce', 0.72);
insert into customers (cname, city, discnt) values ('Joseph Ross', 'Shimotoda', 0.26);
insert into customers (cname, city, discnt) values ('Douglas Lopez', 'Venta', null);
insert into customers (cname, city, discnt) values ('Bobby Gomez', 'La Garenne-Colombes', null);
insert into customers (cname, city, discnt) values ('Donna Weaver', 'Mysiadło', null);
insert into customers (cname, city, discnt) values ('Anthony Little', 'Taoyuan', 0.85);
insert into customers (cname, city, discnt) values ('Victor Phillips', 'Lindavista', 0.14);
insert into customers (cname, city, discnt) values ('Joyce Medina', 'Tagdanua', null);
insert into customers (cname, city, discnt) values ('Benjamin Jones', 'Yakovlevskoye', null);
insert into customers (cname, city, discnt) values ('Benjamin Hughes', 'Hiratachō', null);
insert into customers (cname, city, discnt) values ('Lillian Palmer', 'Pondokrejo Wetan', 0.76);
insert into customers (cname, city, discnt) values ('Jeffrey Martinez', 'Chicago', null);
insert into customers (cname, city, discnt) values ('Stephen Fernandez', 'El Alamo', null);
insert into customers (cname, city, discnt) values ('Clarence Rice', 'Reims', null);
insert into customers (cname, city, discnt) values ('Catherine Alvarez', 'Buliran Segundo', null);
insert into customers (cname, city, discnt) values ('Robin Gray', 'Changshou', 0.06);
insert into customers (cname, city, discnt) values ('Albert Cox', 'Melchor Ocampo', null);
insert into customers (cname, city, discnt) values ('Joshua Wilson', 'Pacaembu', 0.51);
insert into customers (cname, city, discnt) values ('Juan Pierce', 'Kilifi', null);
insert into customers (cname, city, discnt) values ('Henry Duncan', 'Santo Niño', 0.01);
insert into customers (cname, city, discnt) values ('Louise Willis', 'Sironko', null);
insert into customers (cname, city, discnt) values ('Kenneth Williamson', 'Nanjie', 0.97);
insert into customers (cname, city, discnt) values ('Gerald Price', 'Marseille', null);
insert into customers (cname, city, discnt) values ('Brenda Bishop', 'Huainan', null);
insert into customers (cname, city, discnt) values ('Amanda Crawford', 'Zhongzhai', null);
insert into customers (cname, city, discnt) values ('Brandon Berry', 'Manding', 0.97);
insert into customers (cname, city, discnt) values ('Martha West', 'Jiantianjie', null);
insert into customers (cname, city, discnt) values ('Matthew Burke', 'Gosen', 0.27);
insert into customers (cname, city, discnt) values ('Ann Ruiz', 'Longonjo', null);
insert into customers (cname, city, discnt) values ('Billy Banks', 'Oujda', 0.28);
insert into customers (cname, city, discnt) values ('Eric Little', 'Don Tan', 0.84);
insert into customers (cname, city, discnt) values ('Barbara Morrison', 'Wuluquele', 0.3);
insert into customers (cname, city, discnt) values ('Louise Alexander', 'Deauville', 0.68);
insert into customers (cname, city, discnt) values ('Melissa Washington', 'Lihu', null);
insert into customers (cname, city, discnt) values ('Roy Webb', 'Estacion', null);
insert into customers (cname, city, discnt) values ('Brian Bradley', 'Rudna', null);
insert into customers (cname, city, discnt) values ('Earl Henderson', 'Wakimachi', 0.79);
insert into customers (cname, city, discnt) values ('Ann Ward', 'Huangxi', 0.81);
insert into customers (cname, city, discnt) values ('Dennis Bailey', 'Pelópion', 0.64);
insert into customers (cname, city, discnt) values ('Earl Vasquez', 'Cañuelas', 0.49);
insert into customers (cname, city, discnt) values ('Carl Rogers', 'Pulosari', null);
insert into customers (cname, city, discnt) values ('Russell Lane', 'Jawf al Maqbābah', null);
insert into customers (cname, city, discnt) values ('Larry Richards', 'Antipolo', null);
insert into customers (cname, city, discnt) values ('Jose Scott', 'Ronneby', null);
insert into customers (cname, city, discnt) values ('Lillian Webb', 'Sidorejo', null);
insert into customers (cname, city, discnt) values ('Donald Cunningham', 'Bagumbayan', null);
insert into customers (cname, city, discnt) values ('Paul Banks', 'Ramada', null);
insert into customers (cname, city, discnt) values ('Emily Burns', 'Smyshlyayevka', null);
insert into customers (cname, city, discnt) values ('Lisa Barnes', 'Perštejn', 0.61);
insert into customers (cname, city, discnt) values ('Michelle Burns', 'Kotikawatta', null);
insert into customers (cname, city, discnt) values ('Cynthia Berry', 'Krinichnaya', null);
insert into customers (cname, city, discnt) values ('Kathy Ruiz', 'Takeo', 0.28);
insert into customers (cname, city, discnt) values ('Anne Hill', 'Telhado', null);
insert into customers (cname, city, discnt) values ('Walter Fuller', 'Cimanggu Girang', null);
insert into customers (cname, city, discnt) values ('Matthew Myers', 'Vizal San Pablo', 0.1);
insert into customers (cname, city, discnt) values ('Adam Wood', 'Obama', 0.05);
insert into customers (cname, city, discnt) values ('Helen Rodriguez', 'Koran', null);
insert into customers (cname, city, discnt) values ('Larry Franklin', 'Dresi Wetan', 0.43);
insert into customers (cname, city, discnt) values ('Jacqueline Phillips', 'Nikísiani', null);
insert into customers (cname, city, discnt) values ('Henry Boyd', 'Gaoshan', 0.39);
insert into customers (cname, city, discnt) values ('Debra Knight', 'Shikhany', 0.3);
insert into customers (cname, city, discnt) values ('Donald Cole', 'Huayacundo Arma', null);
insert into customers (cname, city, discnt) values ('Melissa Nichols', 'Banjar Sandinggianyar', null);
insert into customers (cname, city, discnt) values ('Fred Sullivan', 'Thị Trấn Yên Châu', 0.21);
insert into customers (cname, city, discnt) values ('Lawrence Miller', 'Sozopol', null);
insert into customers (cname, city, discnt) values ('Fred Ferguson', 'Montijo', null);
insert into customers (cname, city, discnt) values ('Gary Franklin', 'Qiying', null);
insert into customers (cname, city, discnt) values ('Lawrence Willis', 'Kusatsu', null);
insert into customers (cname, city, discnt) values ('Paula Thompson', 'Tīrān', 0.93);
insert into customers (cname, city, discnt) values ('Brian Ray', 'Białaczów', null);
insert into customers (cname, city, discnt) values ('Daniel Woods', 'Vale Covo', null);
insert into customers (cname, city, discnt) values ('Steven Kelley', 'Jacareí', 0.05);
insert into customers (cname, city, discnt) values ('Russell Hudson', 'Hejiang', 0.49);
insert into customers (cname, city, discnt) values ('Alice Warren', 'Larache', null);
insert into customers (cname, city, discnt) values ('Marie Gonzales', 'Guanzhou', 0.32);
insert into customers (cname, city, discnt) values ('Robin Morrison', 'Brinje', null);
insert into customers (cname, city, discnt) values ('Lillian Cooper', 'Savonranta', null);
insert into customers (cname, city, discnt) values ('Ryan Parker', 'Diamantino', null);
insert into customers (cname, city, discnt) values ('Philip Harper', 'Porsgrunn', 0.92);
insert into customers (cname, city, discnt) values ('Andrea Hamilton', 'Taboão da Serra', null);
insert into customers (cname, city, discnt) values ('Alan Barnes', 'Ljukovo', 0.23);
insert into customers (cname, city, discnt) values ('Albert Wagner', 'Yeyik', 0.91);
insert into customers (cname, city, discnt) values ('Mildred Howell', 'Baini', null);
insert into customers (cname, city, discnt) values ('Carol Fisher', 'Bocos', 0.71);
insert into customers (cname, city, discnt) values ('Jose Robertson', 'Libertad', 0.72);
insert into customers (cname, city, discnt) values ('James Rose', 'Bardo', null);
insert into customers (cname, city, discnt) values ('Rebecca Burns', 'Blagoveshchenka', null);
insert into customers (cname, city, discnt) values ('Irene Watkins', 'Santa Luzia', null);
insert into customers (cname, city, discnt) values ('Benjamin Alexander', 'Dingchang', 0.8);
insert into customers (cname, city, discnt) values ('Alice Jones', 'Rupe', 0.56);
insert into customers (cname, city, discnt) values ('Beverly Vasquez', 'Marulanda', 0.67);
insert into customers (cname, city, discnt) values ('Theresa Lee', 'Aianí', null);
insert into customers (cname, city, discnt) values ('Pamela Hernandez', 'Zephyrhills', null);
insert into customers (cname, city, discnt) values ('Gloria Fuller', 'Marumori', null);
insert into customers (cname, city, discnt) values ('James Harrison', 'Jampang Tengah', null);
insert into customers (cname, city, discnt) values ('Earl Little', 'Yinying', null);
insert into customers (cname, city, discnt) values ('Billy Chapman', 'Sunan', 0.42);
insert into customers (cname, city, discnt) values ('Angela Sanders', 'Hengli', null);
insert into customers (cname, city, discnt) values ('Martha Gilbert', 'Jardín América', null);
insert into customers (cname, city, discnt) values ('Kevin Mccoy', 'Jinfeng', null);
insert into customers (cname, city, discnt) values ('Katherine Henderson', 'Nha Trang', 0.67);
insert into customers (cname, city, discnt) values ('Sean Arnold', 'Zagazig', null);
insert into customers (cname, city, discnt) values ('Amanda Porter', 'Tekikbanyuurip', null);
insert into customers (cname, city, discnt) values ('Anna Brooks', 'pamas', null);
insert into customers (cname, city, discnt) values ('Janet Williamson', 'Quanjiang', null);
insert into customers (cname, city, discnt) values ('Bruce Gordon', 'Futu', null);
insert into customers (cname, city, discnt) values ('Paul Payne', 'San Cristobal', null);
insert into customers (cname, city, discnt) values ('Donald Garrett', 'Chafé', null);
insert into customers (cname, city, discnt) values ('Maria Rose', 'Besançon', 0.09);
insert into customers (cname, city, discnt) values ('Karen Baker', 'Qiancang', null);
insert into customers (cname, city, discnt) values ('Jesse Ross', 'Hefu', 0.13);
insert into customers (cname, city, discnt) values ('Antonio Campbell', 'Nabire', null);
insert into customers (cname, city, discnt) values ('Samuel Harvey', 'Křížová', 0.36);
insert into customers (cname, city, discnt) values ('Ronald Martinez', 'Pasto', null);
insert into customers (cname, city, discnt) values ('Michelle Lewis', 'Yangdian', 0.13);
insert into customers (cname, city, discnt) values ('Janet Moore', 'Dadiya', 0.11);
insert into customers (cname, city, discnt) values ('John Hart', 'De la Paz', null);
insert into customers (cname, city, discnt) values ('Christina West', 'Sankera', null);
insert into customers (cname, city, discnt) values ('Linda Wilson', 'Maasin', 0.55);
insert into customers (cname, city, discnt) values ('Todd Flores', 'Bulu', 0.56);
insert into customers (cname, city, discnt) values ('Kathleen Reynolds', 'Oslo', null);
insert into customers (cname, city, discnt) values ('Ronald Peters', 'Trstenik', null);
insert into customers (cname, city, discnt) values ('Frances Turner', 'Zoumachang', 0.49);
insert into customers (cname, city, discnt) values ('Joe Morales', 'Mataraben', 0.88);
insert into customers (cname, city, discnt) values ('Irene Webb', 'Aracati', 0.65);
insert into customers (cname, city, discnt) values ('Terry Morris', 'Būrkah', null);
insert into customers (cname, city, discnt) values ('Patrick Schmidt', 'Ostrów Wielkopolski', null);
insert into customers (cname, city, discnt) values ('Fred Fields', 'Zgłobień', 0.78);
insert into customers (cname, city, discnt) values ('Maria Ramos', 'Makur', null);
insert into customers (cname, city, discnt) values ('Deborah Peterson', 'Chalandrítsa', null);
insert into customers (cname, city, discnt) values ('Walter Kim', 'Iligan City', 0.85);
insert into customers (cname, city, discnt) values ('Antonio Nichols', 'Ilama', 0.57);
insert into customers (cname, city, discnt) values ('Earl Hunter', 'San Isidro', 0.54);
insert into customers (cname, city, discnt) values ('Alan King', 'Spas-Zaulok', 0.96);
insert into customers (cname, city, discnt) values ('David Garza', 'Houmt Souk', null);
insert into customers (cname, city, discnt) values ('Gerald Simpson', 'Montijo', 0.47);
insert into customers (cname, city, discnt) values ('Joan Long', 'Pandan', null);
insert into customers (cname, city, discnt) values ('Debra Bishop', 'Jinglou', null);
insert into customers (cname, city, discnt) values ('Ruth Schmidt', 'Klapagada', 0.2);
insert into customers (cname, city, discnt) values ('Harold Holmes', 'La Cruz', 0.75);
insert into customers (cname, city, discnt) values ('Andrew Jordan', 'Machikou', 0.3);
insert into customers (cname, city, discnt) values ('Teresa Cunningham', 'Aquin', null);
insert into customers (cname, city, discnt) values ('Fred Morgan', 'Randuagung', 0.59);
insert into customers (cname, city, discnt) values ('Keith Lee', 'Río de Oro', null);
insert into customers (cname, city, discnt) values ('Emily Ford', 'Dvinskoy', null);
insert into customers (cname, city, discnt) values ('Alice Dean', 'Manhush', 0.92);
insert into customers (cname, city, discnt) values ('Antonio Torres', 'Xihe', 0.93);
insert into customers (cname, city, discnt) values ('Doris Dean', 'Aheloy', null);
insert into customers (cname, city, discnt) values ('Marie Edwards', 'Laohekou', 0.73);
insert into customers (cname, city, discnt) values ('Katherine Brooks', 'Saravia', 0.81);
insert into customers (cname, city, discnt) values ('Theresa Reynolds', 'Loreto', 0.36);
insert into customers (cname, city, discnt) values ('Daniel Gonzalez', 'Zheng’an', 0.46);
insert into customers (cname, city, discnt) values ('Jimmy Hill', 'Chernelytsya', 0.96);
insert into customers (cname, city, discnt) values ('Anthony Carr', 'Nangabulik', null);
insert into customers (cname, city, discnt) values ('Donna Lawson', 'Los Andes', null);
insert into customers (cname, city, discnt) values ('Arthur Bell', 'Tsowkêy', 0.61);
insert into customers (cname, city, discnt) values ('Gary Boyd', 'Strassen', 0.34);
insert into customers (cname, city, discnt) values ('Donald Simmons', 'San Carlos', 0.58);
insert into customers (cname, city, discnt) values ('Louis Mitchell', 'Palca', 0.42);
insert into customers (cname, city, discnt) values ('Elizabeth Holmes', 'George Hill', 0.57);
insert into customers (cname, city, discnt) values ('Adam Cole', 'Geghanist', 0.92);
insert into customers (cname, city, discnt) values ('Billy Wells', 'Berģi', 0.01);
insert into customers (cname, city, discnt) values ('Joseph Scott', 'Trzcinica', 0.25);
insert into customers (cname, city, discnt) values ('Sean Hanson', 'Emiliano Zapata', null);
insert into customers (cname, city, discnt) values ('Sean West', 'Sámi', 0.37);
insert into customers (cname, city, discnt) values ('Howard Nichols', 'Koryukivka', null);
insert into customers (cname, city, discnt) values ('Margaret Larson', 'Landskrona', 0.14);
insert into customers (cname, city, discnt) values ('Maria Sanders', 'Pil’na', 0.18);
insert into customers (cname, city, discnt) values ('Mildred Perry', 'Houston', 0.53);
insert into customers (cname, city, discnt) values ('Matthew Martin', 'Villa Hayes', null);
insert into customers (cname, city, discnt) values ('Jimmy Baker', 'Itacarambi', null);
insert into customers (cname, city, discnt) values ('Robin Hayes', 'Muqi', null);
insert into customers (cname, city, discnt) values ('Christina Jacobs', 'Koronganayam', 0.38);
insert into customers (cname, city, discnt) values ('Wayne Thomas', 'Banepa', 0.22);
insert into customers (cname, city, discnt) values ('Jessica Bradley', 'Staryy Urukh', null);
insert into customers (cname, city, discnt) values ('Keith Pierce', 'Xinminxiang', 0.48);
insert into customers (cname, city, discnt) values ('John Shaw', 'El Rosario', null);
insert into customers (cname, city, discnt) values ('Marilyn Ray', 'Strellc i Epërm', 0.58);
insert into customers (cname, city, discnt) values ('Kathleen Daniels', 'Sumber', 0.31);
insert into customers (cname, city, discnt) values ('Susan Kelley', 'Hannō', 0.23);
insert into customers (cname, city, discnt) values ('Stephen Roberts', 'Gostimë', null);
insert into customers (cname, city, discnt) values ('Marilyn Ryan', 'Fredericton', null);
insert into customers (cname, city, discnt) values ('Laura Baker', 'Daxi', null);
insert into customers (cname, city, discnt) values ('Beverly Bailey', 'Romblon', null);
insert into customers (cname, city, discnt) values ('Wayne Reyes', 'Panyindangan', 0.7);
insert into customers (cname, city, discnt) values ('Emily Sullivan', 'Izmaylovo', null);
insert into customers (cname, city, discnt) values ('Kenneth Moreno', 'Osias', null);
insert into customers (cname, city, discnt) values ('Joshua Warren', 'Coronel Belisle', 0.16);
insert into customers (cname, city, discnt) values ('Teresa Riley', 'Ban Ko Lan', 0.99);
insert into customers (cname, city, discnt) values ('Sandra Williams', 'Yangchun', null);
insert into customers (cname, city, discnt) values ('Jason Moreno', 'Rybinsk', null);
insert into customers (cname, city, discnt) values ('Lois Freeman', 'Teplice', 0.41);
insert into customers (cname, city, discnt) values ('Amanda Allen', 'Ziguinchor', null);
insert into customers (cname, city, discnt) values ('Christine Hansen', 'Olenegorsk', 0.44);
insert into customers (cname, city, discnt) values ('Raymond Stevens', 'Obrenovac', 0.06);
insert into customers (cname, city, discnt) values ('Cheryl Gordon', 'Perniö', null);
insert into customers (cname, city, discnt) values ('Christopher Lewis', 'Liperi', 0.91);
insert into customers (cname, city, discnt) values ('Rebecca Carroll', 'Łąka Prudnicka', 0.16);
insert into customers (cname, city, discnt) values ('Walter Bailey', 'Wanlongshan', 0.59);
insert into customers (cname, city, discnt) values ('Craig Ross', 'Stockholm', null);
insert into customers (cname, city, discnt) values ('Jack Brown', 'Verin Artashat', null);
insert into customers (cname, city, discnt) values ('Stephanie Vasquez', 'Chã Grande', 0.16);
insert into customers (cname, city, discnt) values ('Edward Hill', 'El Bauga', null);
insert into customers (cname, city, discnt) values ('Ernest Tucker', 'Thị Trấn Trùng Khánh', 0.16);
insert into customers (cname, city, discnt) values ('Sarah Armstrong', 'Hola Prystan’', 0.09);
insert into customers (cname, city, discnt) values ('Gary Long', 'Songkhla', null);
insert into customers (cname, city, discnt) values ('Kimberly Bell', 'Lüxiang', 0.17);
insert into customers (cname, city, discnt) values ('Evelyn Crawford', 'Carpiquet', null);
insert into customers (cname, city, discnt) values ('Amy Wheeler', 'Waipawa', 0.74);
insert into customers (cname, city, discnt) values ('Russell Mitchell', 'Barueri', null);
insert into customers (cname, city, discnt) values ('Russell Gray', 'Kediren', null);
insert into customers (cname, city, discnt) values ('Roger Wilson', 'Mamedkala', null);
insert into customers (cname, city, discnt) values ('Arthur Evans', 'Yangdang', 0.49);
insert into customers (cname, city, discnt) values ('Steve Mitchell', 'Qiaogu', null);
insert into customers (cname, city, discnt) values ('Martha Fernandez', 'Uddevalla', null);
insert into customers (cname, city, discnt) values ('Brian Mendoza', 'Virje', null);
insert into customers (cname, city, discnt) values ('Paul Wells', 'Bergville', 0.88);
insert into customers (cname, city, discnt) values ('Matthew Greene', 'Perches', 0.06);
insert into customers (cname, city, discnt) values ('Doris Morrison', 'Paris 16', 0.25);
insert into customers (cname, city, discnt) values ('Lawrence Gilbert', 'Donomulyo', 0.73);
insert into customers (cname, city, discnt) values ('Christopher Richardson', 'Mikhaylovsk', 0.66);
insert into customers (cname, city, discnt) values ('Jeffrey Henry', 'Troparëvo', 0.32);
insert into customers (cname, city, discnt) values ('Philip Gibson', 'Lorraine', 0.6);
insert into customers (cname, city, discnt) values ('Louise Berry', 'Li’an', null);
insert into customers (cname, city, discnt) values ('Keith Murphy', 'Mykonos', null);
insert into customers (cname, city, discnt) values ('David Perez', 'Kohāt', null);
insert into customers (cname, city, discnt) values ('Cheryl Stewart', 'Molave', null);
insert into customers (cname, city, discnt) values ('Fred Morgan', 'Bunigeulis', 0.26);
insert into customers (cname, city, discnt) values ('Joan Meyer', 'Ban Huai Thalaeng', 0.0);
insert into customers (cname, city, discnt) values ('Joan Duncan', 'Boucinha', null);
insert into customers (cname, city, discnt) values ('Matthew Carroll', 'Uummannaq', null);
insert into customers (cname, city, discnt) values ('Frank Reed', 'Xihuachi', null);
insert into customers (cname, city, discnt) values ('Brandon Armstrong', 'Guaíba', null);
insert into customers (cname, city, discnt) values ('Robin Graham', 'Kalamangog', null);
insert into customers (cname, city, discnt) values ('Patricia Kim', 'Kirkland', null);
insert into customers (cname, city, discnt) values ('Rachel Myers', 'Krasnyy Klyuch', 0.41);
insert into customers (cname, city, discnt) values ('Brian Reid', 'Soure', 0.36);
insert into customers (cname, city, discnt) values ('Alice Tucker', 'Guayaybi', 0.91);
insert into customers (cname, city, discnt) values ('Brenda Burns', 'Lhabupu', 0.72);
insert into customers (cname, city, discnt) values ('Lisa Mason', 'Natividade', null);
insert into customers (cname, city, discnt) values ('Paula Pierce', 'Cololaca', 0.34);
insert into customers (cname, city, discnt) values ('Bruce Collins', 'Pule', 0.54);
insert into customers (cname, city, discnt) values ('Joseph Long', 'Bentar', null);
insert into customers (cname, city, discnt) values ('Eric Anderson', 'Lebak', 0.75);
insert into customers (cname, city, discnt) values ('Carolyn Hill', 'Labuan', null);
insert into customers (cname, city, discnt) values ('Ruby Mcdonald', 'Chucatamani', 0.13);
insert into customers (cname, city, discnt) values ('Sean Daniels', 'Poxin', 0.8);
insert into customers (cname, city, discnt) values ('Willie Mitchell', 'Vila Fria', null);
insert into customers (cname, city, discnt) values ('Lawrence Tucker', 'Nashtā Rūd', null);
insert into customers (cname, city, discnt) values ('Rebecca George', 'Kaélé', null);
insert into customers (cname, city, discnt) values ('John Meyer', 'Tochio-honchō', 0.89);
insert into customers (cname, city, discnt) values ('Judith Moreno', 'Kandang Timur', 0.81);
insert into customers (cname, city, discnt) values ('Amanda Gray', 'Goge', 0.05);
insert into customers (cname, city, discnt) values ('Thomas Turner', 'Toba', 0.64);
insert into customers (cname, city, discnt) values ('Betty Reed', 'Nizhniy Tagil', 0.79);
insert into customers (cname, city, discnt) values ('Jeremy Mcdonald', 'Embarcación', 0.43);
insert into customers (cname, city, discnt) values ('Johnny Hill', 'Paulo Afonso', null);
insert into customers (cname, city, discnt) values ('Harold Bradley', 'Garisul', null);
insert into customers (cname, city, discnt) values ('Carol Lopez', 'Diekirch', 0.4);
insert into customers (cname, city, discnt) values ('Jimmy Ellis', 'Kepel', null);
insert into customers (cname, city, discnt) values ('Elizabeth Jackson', 'Lappi', 0.69);
insert into customers (cname, city, discnt) values ('Chris Wagner', 'Thị Trấn Bắc Yên', null);
insert into customers (cname, city, discnt) values ('Janice Alexander', 'Wat Bot', null);
insert into customers (cname, city, discnt) values ('Catherine Marshall', 'Medaya', null);
insert into customers (cname, city, discnt) values ('Timothy Wood', 'Majengo', null);
insert into customers (cname, city, discnt) values ('Christina Gutierrez', 'Trondheim', null);
insert into customers (cname, city, discnt) values ('Samuel Ruiz', 'Sipocot', null);
insert into customers (cname, city, discnt) values ('Karen Larson', 'Vawkavysk', 0.25);
insert into customers (cname, city, discnt) values ('Karen Lawson', 'San Antonio', 0.15);
insert into customers (cname, city, discnt) values ('Sarah Barnes', 'Acobamba', null);
insert into customers (cname, city, discnt) values ('Ryan Stevens', 'Waitun', null);
insert into customers (cname, city, discnt) values ('Evelyn Henderson', 'Funza', 0.49);
insert into customers (cname, city, discnt) values ('Jonathan Henry', 'Berlin', 0.5);
insert into customers (cname, city, discnt) values ('Pamela Gordon', 'Tierp', null);
insert into customers (cname, city, discnt) values ('Shirley Flores', 'Náousa', 0.85);
insert into customers (cname, city, discnt) values ('Billy Gonzales', 'Chicacao', 0.05);
insert into customers (cname, city, discnt) values ('Anthony Stanley', 'Prior Velho', null);
insert into customers (cname, city, discnt) values ('Joe Lewis', 'Imulolong', 0.5);
insert into customers (cname, city, discnt) values ('Jean Allen', 'Daugavpils', null);
insert into customers (cname, city, discnt) values ('Gerald Reed', 'Vale Boeiro', 0.84);
insert into customers (cname, city, discnt) values ('Rebecca Hernandez', 'Dahua', null);
insert into customers (cname, city, discnt) values ('Paula Myers', 'Taozhuang', null);
insert into customers (cname, city, discnt) values ('Eugene Wood', 'Igboho', 0.79);
insert into customers (cname, city, discnt) values ('Diane Wells', 'Hudong', 0.54);
insert into customers (cname, city, discnt) values ('Sara Cox', 'Zhongxing', 0.72);
insert into customers (cname, city, discnt) values ('Raymond Warren', 'Couço', 0.44);
insert into customers (cname, city, discnt) values ('Donald Kennedy', 'Dzuunmod', null);
insert into customers (cname, city, discnt) values ('Jennifer Castillo', 'Adzopé', 0.87);
insert into customers (cname, city, discnt) values ('Raymond Knight', 'Aleksandrovka', null);
insert into customers (cname, city, discnt) values ('Bonnie Murphy', 'Bassar', 0.76);
insert into customers (cname, city, discnt) values ('Teresa Evans', 'Hugang', 0.68);
insert into customers (cname, city, discnt) values ('Billy Meyer', 'Stýpsi', null);
insert into customers (cname, city, discnt) values ('Amanda Sanchez', 'Francisco Morato', null);
insert into customers (cname, city, discnt) values ('Ernest Taylor', 'Kota Trieng', null);
insert into customers (cname, city, discnt) values ('Craig Pierce', 'Gudong', null);
insert into customers (cname, city, discnt) values ('Juan Rogers', 'Wuhe Chengguanzhen', 0.44);
insert into customers (cname, city, discnt) values ('Thomas Romero', 'Uppsala', 1.0);
insert into customers (cname, city, discnt) values ('Jonathan Harrison', 'New Shagunnu', 0.49);
insert into customers (cname, city, discnt) values ('Anthony Snyder', 'Uvarovka', null);
insert into customers (cname, city, discnt) values ('Diana Fernandez', 'Ribeira Seca', 0.58);
insert into customers (cname, city, discnt) values ('Catherine Chapman', 'Farasān', null);
insert into customers (cname, city, discnt) values ('Stephanie Holmes', 'Río Gallegos', null);
insert into customers (cname, city, discnt) values ('Gary Matthews', 'Ōzu', null);
insert into customers (cname, city, discnt) values ('Tina Rice', 'Dalsjöfors', null);
insert into customers (cname, city, discnt) values ('Walter Jacobs', 'Telengsari', 0.33);
insert into customers (cname, city, discnt) values ('Lawrence Burton', 'Knivsta', null);
insert into customers (cname, city, discnt) values ('Kathleen Ferguson', 'Fuzihe', 0.81);
insert into customers (cname, city, discnt) values ('Jennifer Powell', 'New Cebu', null);
insert into customers (cname, city, discnt) values ('Jessica Hawkins', 'Kuching', 0.98);
insert into customers (cname, city, discnt) values ('Jack Richardson', 'Culubasa', 0.16);
insert into customers (cname, city, discnt) values ('Arthur Harris', 'Shuinan', null);
insert into customers (cname, city, discnt) values ('Jesse Alvarez', 'Wadi Kidul', null);
insert into customers (cname, city, discnt) values ('Joyce Romero', 'Kayan Hulu', null);
insert into customers (cname, city, discnt) values ('Stephen Franklin', 'Lisków', null);
insert into customers (cname, city, discnt) values ('Bruce King', 'Motygino', null);
insert into customers (cname, city, discnt) values ('Rose Dean', 'Sanjian', 0.77);
insert into customers (cname, city, discnt) values ('Jerry Stephens', 'Songon', 0.2);
insert into customers (cname, city, discnt) values ('Anna Carpenter', 'Nambak Tengah', null);
insert into customers (cname, city, discnt) values ('Theresa Romero', 'Rossosh’', null);
insert into customers (cname, city, discnt) values ('Melissa Gilbert', 'Yangtan', null);
insert into customers (cname, city, discnt) values ('Clarence Pierce', 'Sale', null);
insert into customers (cname, city, discnt) values ('Jerry Gonzales', 'Sobinka', 0.2);
insert into customers (cname, city, discnt) values ('Donald Lawrence', 'Novomoskovsk', 0.28);
insert into customers (cname, city, discnt) values ('Donald Harper', 'Rio Real', 0.11);
insert into customers (cname, city, discnt) values ('Chris West', 'Shizukuishi', 0.89);
insert into customers (cname, city, discnt) values ('Alan Oliver', 'Taimaman', 0.17);
insert into customers (cname, city, discnt) values ('Denise Chapman', 'Lamalera', 0.37);
insert into customers (cname, city, discnt) values ('Carol Kim', 'Sukadami', null);
insert into customers (cname, city, discnt) values ('Cheryl Hudson', 'Yanping', 0.62);
insert into customers (cname, city, discnt) values ('Scott Butler', 'El Quebrachal', 0.18);
insert into customers (cname, city, discnt) values ('Stephanie Lynch', 'Chum Phae', null);
insert into customers (cname, city, discnt) values ('Nancy Harrison', 'Pindobaçu', null);
insert into customers (cname, city, discnt) values ('Victor Frazier', 'Daminggong', null);
insert into customers (cname, city, discnt) values ('Brandon Grant', 'Comalapa', null);
insert into customers (cname, city, discnt) values ('Sarah Wright', 'Oughterard', null);
insert into customers (cname, city, discnt) values ('Dorothy Fields', 'Kōriyama', null);
insert into customers (cname, city, discnt) values ('Pamela Fisher', 'Villaviciosa', 0.57);
insert into customers (cname, city, discnt) values ('Amy Jenkins', 'Al Qanāwiş', 0.65);
insert into customers (cname, city, discnt) values ('Sarah Walker', 'Piran', null);
insert into customers (cname, city, discnt) values ('Paula Morrison', 'Kranggan', null);
insert into customers (cname, city, discnt) values ('Denise Martinez', 'Panjing', 0.99);
insert into customers (cname, city, discnt) values ('Marilyn Reed', 'Costa Rica', 0.85);
insert into customers (cname, city, discnt) values ('Donald Morris', 'Žirovnice', 0.57);
insert into customers (cname, city, discnt) values ('Deborah Hayes', 'Dupi', 0.44);
insert into customers (cname, city, discnt) values ('Julia Ferguson', 'Jardim do Seridó', 0.64);
insert into customers (cname, city, discnt) values ('Adam Boyd', 'Pampa Hermosa', null);
insert into customers (cname, city, discnt) values ('Jason Collins', 'Tovarkovskiy', 0.24);
insert into customers (cname, city, discnt) values ('Roy Morales', 'Untolovo', null);
insert into customers (cname, city, discnt) values ('Barbara Cruz', 'Primorsko-Akhtarsk', null);
insert into customers (cname, city, discnt) values ('Wanda Tucker', 'Huité', 0.79);
insert into customers (cname, city, discnt) values ('Janice Moreno', 'Kankan', null);
insert into customers (cname, city, discnt) values ('Roger Harvey', 'Milán', null);
insert into customers (cname, city, discnt) values ('Kevin Richardson', 'Kolonowskie', 0.72);
insert into customers (cname, city, discnt) values ('Ruth Henderson', 'Wanglu Kulon', null);
insert into customers (cname, city, discnt) values ('Jonathan Cruz', 'Tangxi', null);
insert into customers (cname, city, discnt) values ('Amy Matthews', 'Rosmaninhal', 0.34);
insert into customers (cname, city, discnt) values ('Julie Warren', 'Ramanavichy', null);
insert into customers (cname, city, discnt) values ('Nancy Hunt', 'Pogórze', 0.97);
insert into customers (cname, city, discnt) values ('Antonio Porter', 'Lens', 0.43);
insert into customers (cname, city, discnt) values ('Karen Schmidt', 'Dióni', null);
insert into customers (cname, city, discnt) values ('David Lawrence', 'Nankengzi', 0.86);
insert into customers (cname, city, discnt) values ('Howard Wheeler', 'Akademgorodok', null);
insert into customers (cname, city, discnt) values ('Robin Cole', 'Wrząsowice', 0.94);
insert into customers (cname, city, discnt) values ('Roy Torres', 'Quirinópolis', null);
insert into customers (cname, city, discnt) values ('Roger Reid', 'Paradahan', 1.0);
insert into customers (cname, city, discnt) values ('Fred Russell', 'Petřvald', 0.83);
insert into customers (cname, city, discnt) values ('Deborah Hawkins', 'Shilong', 0.71);
insert into customers (cname, city, discnt) values ('Dorothy Bradley', 'La Cruz', 0.86);
insert into customers (cname, city, discnt) values ('Jennifer Hayes', 'Mandangoa', 0.38);
insert into customers (cname, city, discnt) values ('Julie Cooper', 'Idrija', null);
insert into customers (cname, city, discnt) values ('Ronald Fields', 'Seiça', 0.47);
insert into customers (cname, city, discnt) values ('Diana Gray', 'Chodzież', null);
insert into customers (cname, city, discnt) values ('Joe Washington', 'Dado', 0.09);
insert into customers (cname, city, discnt) values ('Kathryn Vasquez', 'Aţ Ţaybah', 0.93);
insert into customers (cname, city, discnt) values ('Anne Hall', 'Huanggu', null);
insert into customers (cname, city, discnt) values ('Shirley Russell', 'Dinan', 0.77);
insert into customers (cname, city, discnt) values ('Lois Woods', 'Issenye', null);
insert into customers (cname, city, discnt) values ('Julie Thomas', 'Longlisuo', null);
insert into customers (cname, city, discnt) values ('Lawrence Morales', 'Saldanha', 0.48);
insert into customers (cname, city, discnt) values ('Marie Murphy', 'Korydallós', null);
insert into customers (cname, city, discnt) values ('Brenda Wheeler', 'Bayanbaogede', null);
insert into customers (cname, city, discnt) values ('Harry Fox', 'Wewoloe', 0.8);
insert into customers (cname, city, discnt) values ('Jesse Bowman', 'Caledon', null);
insert into customers (cname, city, discnt) values ('Ann Gonzalez', 'Xinshui', null);
insert into customers (cname, city, discnt) values ('Wanda Butler', 'Hepu', 0.59);
insert into customers (cname, city, discnt) values ('Roy Kelley', 'Tacna', 0.77);
insert into customers (cname, city, discnt) values ('Antonio Webb', 'Dzüünbulag', null);
insert into customers (cname, city, discnt) values ('James Fuller', 'La Virginia', null);
insert into customers (cname, city, discnt) values ('Sandra Hudson', 'Stockholm', null);
insert into customers (cname, city, discnt) values ('Debra Shaw', 'Dongshan', 0.74);
insert into customers (cname, city, discnt) values ('Andrea Kim', 'Jalapa', null);
insert into customers (cname, city, discnt) values ('Virginia Gilbert', 'Sancha', 0.79);
insert into customers (cname, city, discnt) values ('Rebecca Alvarez', 'Satsumasendai', 0.69);
insert into customers (cname, city, discnt) values ('Sara Hawkins', 'Chapayeve', 0.35);
insert into customers (cname, city, discnt) values ('Kathryn Rose', 'Kuala Lumpur', 0.01);
insert into customers (cname, city, discnt) values ('Stephanie Foster', 'Daoqiao', null);
insert into customers (cname, city, discnt) values ('Ruth Owens', 'Diriamba', null);
insert into customers (cname, city, discnt) values ('Michelle Peterson', 'Campo de la Cruz', null);
insert into customers (cname, city, discnt) values ('Tina Kelly', 'Yingcheng', null);
insert into customers (cname, city, discnt) values ('Carl Myers', 'Shanghu', null);
insert into customers (cname, city, discnt) values ('Gary Harper', 'Papineauville', null);
insert into customers (cname, city, discnt) values ('Sharon Meyer', 'Jönköping', null);
insert into customers (cname, city, discnt) values ('Michelle Watson', 'Rakaia', null);
insert into customers (cname, city, discnt) values ('Ronald Griffin', 'Qal‘ah-ye Shāhī', 0.67);
insert into customers (cname, city, discnt) values ('Jeffrey Peters', 'Stockholm', 0.85);
insert into customers (cname, city, discnt) values ('Julia Morrison', 'Bilajari', 0.62);
insert into customers (cname, city, discnt) values ('Kimberly Perkins', 'Cipadung', 0.16);
insert into customers (cname, city, discnt) values ('Shirley Wallace', 'Corral', null);
insert into customers (cname, city, discnt) values ('Terry James', 'Sunne', 0.97);
insert into customers (cname, city, discnt) values ('Nicole Lawson', 'Runjin', 0.25);
insert into customers (cname, city, discnt) values ('Donna Moore', 'Karanggintung', null);
insert into customers (cname, city, discnt) values ('Janet Martinez', 'Ust’-Koksa', 0.99);
insert into customers (cname, city, discnt) values ('Brandon Burns', 'Anzhero-Sudzhensk', 0.8);
insert into customers (cname, city, discnt) values ('Ann Greene', 'Minanga Norte', 0.07);
insert into customers (cname, city, discnt) values ('Clarence Lane', 'Tashanta', null);
insert into customers (cname, city, discnt) values ('Steve George', 'Bamusso', null);
insert into customers (cname, city, discnt) values ('Emily James', 'Xinlin', null);
insert into customers (cname, city, discnt) values ('Judith Stewart', 'Yamango', null);
insert into customers (cname, city, discnt) values ('Russell Carroll', 'Vårby', null);
insert into customers (cname, city, discnt) values ('Joshua Andrews', 'Tangwāni', 0.61);
insert into customers (cname, city, discnt) values ('Kimberly Watson', 'Araguari', null);
insert into customers (cname, city, discnt) values ('Stephanie Oliver', 'Tundagan', 0.23);
insert into customers (cname, city, discnt) values ('Randy Evans', 'Sandur', 0.26);
insert into customers (cname, city, discnt) values ('William Mitchell', 'Pofadder', 0.04);
insert into customers (cname, city, discnt) values ('Eric Webb', 'Tarikolot', 0.72);
insert into customers (cname, city, discnt) values ('Charles Russell', 'Ramat Yishay', 0.32);
insert into customers (cname, city, discnt) values ('Kelly Sanders', 'Wangpu', 0.74);
insert into customers (cname, city, discnt) values ('Melissa Shaw', 'Gort', null);
insert into customers (cname, city, discnt) values ('Mary Crawford', 'Valencia', 0.39);
insert into customers (cname, city, discnt) values ('Eric Sims', 'København', null);
insert into customers (cname, city, discnt) values ('Timothy Jackson', 'Cergy-Pontoise', null);
insert into customers (cname, city, discnt) values ('Jimmy Bowman', 'Gentilly', null);
insert into customers (cname, city, discnt) values ('Patricia Williams', 'Lucija', 0.49);
insert into customers (cname, city, discnt) values ('Julia Long', 'Fanrong', 0.47);
insert into customers (cname, city, discnt) values ('Billy Lawson', 'Içara', 0.44);
insert into customers (cname, city, discnt) values ('Lawrence Reyes', 'Skoroszyce', 0.01);
insert into customers (cname, city, discnt) values ('Phillip White', 'Montes', 0.28);
insert into customers (cname, city, discnt) values ('Martin Arnold', 'Gongchenqiao', null);
insert into customers (cname, city, discnt) values ('Larry Alexander', 'Salcedo', null);
insert into customers (cname, city, discnt) values ('Michael Gomez', 'Mafa', null);
insert into customers (cname, city, discnt) values ('Phyllis Payne', 'Cikajang', 0.77);
insert into customers (cname, city, discnt) values ('Carl Ray', 'Yaroslavl', null);
insert into customers (cname, city, discnt) values ('Daniel Evans', 'Draginje', null);
insert into customers (cname, city, discnt) values ('Earl Wallace', 'Příbor', 0.65);
insert into customers (cname, city, discnt) values ('Henry Ramirez', 'Zinder', null);
insert into customers (cname, city, discnt) values ('Edward Clark', 'Boyu', null);
insert into customers (cname, city, discnt) values ('Margaret Long', 'Kanbula', null);
insert into customers (cname, city, discnt) values ('Kenneth Richards', 'Red Hill', 0.15);
insert into customers (cname, city, discnt) values ('Ralph Hayes', 'Cilolohan', 0.28);
insert into customers (cname, city, discnt) values ('Mildred West', 'Yaring', 0.37);
insert into customers (cname, city, discnt) values ('Terry Vasquez', 'Busia', null);
insert into customers (cname, city, discnt) values ('Wayne Larson', 'Profítis Ilías', 0.1);
insert into customers (cname, city, discnt) values ('Amy Scott', 'Santiago', null);
